// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Administration module

	public static java.lang.String getWM_GUIDANCE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Administration.WM_GUIDANCE");
	}
}