// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package zgws_cust_get_srv.proxies;

public class Customer extends sapodataconnector.proxies.OdataObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ZGWS_cust_GET_SRV.Customer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Kunnr("Kunnr"),
		Land1("Land1"),
		Name1("Name1"),
		Name2("Name2"),
		Pstlz("Pstlz"),
		Regio("Regio"),
		Anred("Anred"),
		Ktokd("Ktokd"),
		Lifnr("Lifnr"),
		Sperr("Sperr"),
		Sperr2("Sperr2"),
		Stcd1("Stcd1"),
		Stcd2("Stcd2"),
		Vbund("Vbund"),
		Sort1("Sort1"),
		Sort2("Sort2"),
		Str_suppl3("Str_suppl3"),
		Location("Location"),
		City1("City1"),
		City2("City2"),
		Tel_number("Tel_number"),
		Smtp_addr("Smtp_addr"),
		Street("Street"),
		Bukrs("Bukrs"),
		Akont("Akont"),
		Zterm("Zterm"),
		Longitude("Longitude"),
		Latitude("Latitude"),
		Precisid("Precisid"),
		meta_objectURI("meta_objectURI"),
		meta_etag("meta_etag"),
		OdataObject_ResultInfo("SAPODataConnector.OdataObject_ResultInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ZGWS_cust_GET_SRV.Customer"));
	}

	protected Customer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject)
	{
		super(context, customerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("ZGWS_cust_GET_SRV.Customer", customerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ZGWS_cust_GET_SRV.Customer");
	}

	/**
	 * @deprecated Use 'Customer.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static zgws_cust_get_srv.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return zgws_cust_get_srv.proxies.Customer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static zgws_cust_get_srv.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new zgws_cust_get_srv.proxies.Customer(context, mendixObject);
	}

	public static zgws_cust_get_srv.proxies.Customer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return zgws_cust_get_srv.proxies.Customer.initialize(context, mendixObject);
	}

	/**
	 * @return value of Kunnr
	 */
	public final java.lang.String getKunnr()
	{
		return getKunnr(getContext());
	}

	/**
	 * @param context
	 * @return value of Kunnr
	 */
	public final java.lang.String getKunnr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kunnr.toString());
	}

	/**
	 * Set value of Kunnr
	 * @param kunnr
	 */
	public final void setKunnr(java.lang.String kunnr)
	{
		setKunnr(getContext(), kunnr);
	}

	/**
	 * Set value of Kunnr
	 * @param context
	 * @param kunnr
	 */
	public final void setKunnr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kunnr)
	{
		getMendixObject().setValue(context, MemberNames.Kunnr.toString(), kunnr);
	}

	/**
	 * @return value of Land1
	 */
	public final java.lang.String getLand1()
	{
		return getLand1(getContext());
	}

	/**
	 * @param context
	 * @return value of Land1
	 */
	public final java.lang.String getLand1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Land1.toString());
	}

	/**
	 * Set value of Land1
	 * @param land1
	 */
	public final void setLand1(java.lang.String land1)
	{
		setLand1(getContext(), land1);
	}

	/**
	 * Set value of Land1
	 * @param context
	 * @param land1
	 */
	public final void setLand1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String land1)
	{
		getMendixObject().setValue(context, MemberNames.Land1.toString(), land1);
	}

	/**
	 * @return value of Name1
	 */
	public final java.lang.String getName1()
	{
		return getName1(getContext());
	}

	/**
	 * @param context
	 * @return value of Name1
	 */
	public final java.lang.String getName1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name1.toString());
	}

	/**
	 * Set value of Name1
	 * @param name1
	 */
	public final void setName1(java.lang.String name1)
	{
		setName1(getContext(), name1);
	}

	/**
	 * Set value of Name1
	 * @param context
	 * @param name1
	 */
	public final void setName1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name1)
	{
		getMendixObject().setValue(context, MemberNames.Name1.toString(), name1);
	}

	/**
	 * @return value of Name2
	 */
	public final java.lang.String getName2()
	{
		return getName2(getContext());
	}

	/**
	 * @param context
	 * @return value of Name2
	 */
	public final java.lang.String getName2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name2.toString());
	}

	/**
	 * Set value of Name2
	 * @param name2
	 */
	public final void setName2(java.lang.String name2)
	{
		setName2(getContext(), name2);
	}

	/**
	 * Set value of Name2
	 * @param context
	 * @param name2
	 */
	public final void setName2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name2)
	{
		getMendixObject().setValue(context, MemberNames.Name2.toString(), name2);
	}

	/**
	 * @return value of Pstlz
	 */
	public final java.lang.String getPstlz()
	{
		return getPstlz(getContext());
	}

	/**
	 * @param context
	 * @return value of Pstlz
	 */
	public final java.lang.String getPstlz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Pstlz.toString());
	}

	/**
	 * Set value of Pstlz
	 * @param pstlz
	 */
	public final void setPstlz(java.lang.String pstlz)
	{
		setPstlz(getContext(), pstlz);
	}

	/**
	 * Set value of Pstlz
	 * @param context
	 * @param pstlz
	 */
	public final void setPstlz(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pstlz)
	{
		getMendixObject().setValue(context, MemberNames.Pstlz.toString(), pstlz);
	}

	/**
	 * @return value of Regio
	 */
	public final java.lang.String getRegio()
	{
		return getRegio(getContext());
	}

	/**
	 * @param context
	 * @return value of Regio
	 */
	public final java.lang.String getRegio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Regio.toString());
	}

	/**
	 * Set value of Regio
	 * @param regio
	 */
	public final void setRegio(java.lang.String regio)
	{
		setRegio(getContext(), regio);
	}

	/**
	 * Set value of Regio
	 * @param context
	 * @param regio
	 */
	public final void setRegio(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String regio)
	{
		getMendixObject().setValue(context, MemberNames.Regio.toString(), regio);
	}

	/**
	 * @return value of Anred
	 */
	public final java.lang.String getAnred()
	{
		return getAnred(getContext());
	}

	/**
	 * @param context
	 * @return value of Anred
	 */
	public final java.lang.String getAnred(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Anred.toString());
	}

	/**
	 * Set value of Anred
	 * @param anred
	 */
	public final void setAnred(java.lang.String anred)
	{
		setAnred(getContext(), anred);
	}

	/**
	 * Set value of Anred
	 * @param context
	 * @param anred
	 */
	public final void setAnred(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String anred)
	{
		getMendixObject().setValue(context, MemberNames.Anred.toString(), anred);
	}

	/**
	 * @return value of Ktokd
	 */
	public final java.lang.String getKtokd()
	{
		return getKtokd(getContext());
	}

	/**
	 * @param context
	 * @return value of Ktokd
	 */
	public final java.lang.String getKtokd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ktokd.toString());
	}

	/**
	 * Set value of Ktokd
	 * @param ktokd
	 */
	public final void setKtokd(java.lang.String ktokd)
	{
		setKtokd(getContext(), ktokd);
	}

	/**
	 * Set value of Ktokd
	 * @param context
	 * @param ktokd
	 */
	public final void setKtokd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ktokd)
	{
		getMendixObject().setValue(context, MemberNames.Ktokd.toString(), ktokd);
	}

	/**
	 * @return value of Lifnr
	 */
	public final java.lang.String getLifnr()
	{
		return getLifnr(getContext());
	}

	/**
	 * @param context
	 * @return value of Lifnr
	 */
	public final java.lang.String getLifnr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Lifnr.toString());
	}

	/**
	 * Set value of Lifnr
	 * @param lifnr
	 */
	public final void setLifnr(java.lang.String lifnr)
	{
		setLifnr(getContext(), lifnr);
	}

	/**
	 * Set value of Lifnr
	 * @param context
	 * @param lifnr
	 */
	public final void setLifnr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lifnr)
	{
		getMendixObject().setValue(context, MemberNames.Lifnr.toString(), lifnr);
	}

	/**
	 * @return value of Sperr
	 */
	public final java.lang.String getSperr()
	{
		return getSperr(getContext());
	}

	/**
	 * @param context
	 * @return value of Sperr
	 */
	public final java.lang.String getSperr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sperr.toString());
	}

	/**
	 * Set value of Sperr
	 * @param sperr
	 */
	public final void setSperr(java.lang.String sperr)
	{
		setSperr(getContext(), sperr);
	}

	/**
	 * Set value of Sperr
	 * @param context
	 * @param sperr
	 */
	public final void setSperr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sperr)
	{
		getMendixObject().setValue(context, MemberNames.Sperr.toString(), sperr);
	}

	/**
	 * @return value of Sperr2
	 */
	public final java.lang.String getSperr2()
	{
		return getSperr2(getContext());
	}

	/**
	 * @param context
	 * @return value of Sperr2
	 */
	public final java.lang.String getSperr2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sperr2.toString());
	}

	/**
	 * Set value of Sperr2
	 * @param sperr2
	 */
	public final void setSperr2(java.lang.String sperr2)
	{
		setSperr2(getContext(), sperr2);
	}

	/**
	 * Set value of Sperr2
	 * @param context
	 * @param sperr2
	 */
	public final void setSperr2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sperr2)
	{
		getMendixObject().setValue(context, MemberNames.Sperr2.toString(), sperr2);
	}

	/**
	 * @return value of Stcd1
	 */
	public final java.lang.String getStcd1()
	{
		return getStcd1(getContext());
	}

	/**
	 * @param context
	 * @return value of Stcd1
	 */
	public final java.lang.String getStcd1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Stcd1.toString());
	}

	/**
	 * Set value of Stcd1
	 * @param stcd1
	 */
	public final void setStcd1(java.lang.String stcd1)
	{
		setStcd1(getContext(), stcd1);
	}

	/**
	 * Set value of Stcd1
	 * @param context
	 * @param stcd1
	 */
	public final void setStcd1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stcd1)
	{
		getMendixObject().setValue(context, MemberNames.Stcd1.toString(), stcd1);
	}

	/**
	 * @return value of Stcd2
	 */
	public final java.lang.String getStcd2()
	{
		return getStcd2(getContext());
	}

	/**
	 * @param context
	 * @return value of Stcd2
	 */
	public final java.lang.String getStcd2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Stcd2.toString());
	}

	/**
	 * Set value of Stcd2
	 * @param stcd2
	 */
	public final void setStcd2(java.lang.String stcd2)
	{
		setStcd2(getContext(), stcd2);
	}

	/**
	 * Set value of Stcd2
	 * @param context
	 * @param stcd2
	 */
	public final void setStcd2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stcd2)
	{
		getMendixObject().setValue(context, MemberNames.Stcd2.toString(), stcd2);
	}

	/**
	 * @return value of Vbund
	 */
	public final java.lang.String getVbund()
	{
		return getVbund(getContext());
	}

	/**
	 * @param context
	 * @return value of Vbund
	 */
	public final java.lang.String getVbund(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Vbund.toString());
	}

	/**
	 * Set value of Vbund
	 * @param vbund
	 */
	public final void setVbund(java.lang.String vbund)
	{
		setVbund(getContext(), vbund);
	}

	/**
	 * Set value of Vbund
	 * @param context
	 * @param vbund
	 */
	public final void setVbund(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vbund)
	{
		getMendixObject().setValue(context, MemberNames.Vbund.toString(), vbund);
	}

	/**
	 * @return value of Sort1
	 */
	public final java.lang.String getSort1()
	{
		return getSort1(getContext());
	}

	/**
	 * @param context
	 * @return value of Sort1
	 */
	public final java.lang.String getSort1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sort1.toString());
	}

	/**
	 * Set value of Sort1
	 * @param sort1
	 */
	public final void setSort1(java.lang.String sort1)
	{
		setSort1(getContext(), sort1);
	}

	/**
	 * Set value of Sort1
	 * @param context
	 * @param sort1
	 */
	public final void setSort1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sort1)
	{
		getMendixObject().setValue(context, MemberNames.Sort1.toString(), sort1);
	}

	/**
	 * @return value of Sort2
	 */
	public final java.lang.String getSort2()
	{
		return getSort2(getContext());
	}

	/**
	 * @param context
	 * @return value of Sort2
	 */
	public final java.lang.String getSort2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sort2.toString());
	}

	/**
	 * Set value of Sort2
	 * @param sort2
	 */
	public final void setSort2(java.lang.String sort2)
	{
		setSort2(getContext(), sort2);
	}

	/**
	 * Set value of Sort2
	 * @param context
	 * @param sort2
	 */
	public final void setSort2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sort2)
	{
		getMendixObject().setValue(context, MemberNames.Sort2.toString(), sort2);
	}

	/**
	 * @return value of Str_suppl3
	 */
	public final java.lang.String getStr_suppl3()
	{
		return getStr_suppl3(getContext());
	}

	/**
	 * @param context
	 * @return value of Str_suppl3
	 */
	public final java.lang.String getStr_suppl3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Str_suppl3.toString());
	}

	/**
	 * Set value of Str_suppl3
	 * @param str_suppl3
	 */
	public final void setStr_suppl3(java.lang.String str_suppl3)
	{
		setStr_suppl3(getContext(), str_suppl3);
	}

	/**
	 * Set value of Str_suppl3
	 * @param context
	 * @param str_suppl3
	 */
	public final void setStr_suppl3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String str_suppl3)
	{
		getMendixObject().setValue(context, MemberNames.Str_suppl3.toString(), str_suppl3);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of City1
	 */
	public final java.lang.String getCity1()
	{
		return getCity1(getContext());
	}

	/**
	 * @param context
	 * @return value of City1
	 */
	public final java.lang.String getCity1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City1.toString());
	}

	/**
	 * Set value of City1
	 * @param city1
	 */
	public final void setCity1(java.lang.String city1)
	{
		setCity1(getContext(), city1);
	}

	/**
	 * Set value of City1
	 * @param context
	 * @param city1
	 */
	public final void setCity1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city1)
	{
		getMendixObject().setValue(context, MemberNames.City1.toString(), city1);
	}

	/**
	 * @return value of City2
	 */
	public final java.lang.String getCity2()
	{
		return getCity2(getContext());
	}

	/**
	 * @param context
	 * @return value of City2
	 */
	public final java.lang.String getCity2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City2.toString());
	}

	/**
	 * Set value of City2
	 * @param city2
	 */
	public final void setCity2(java.lang.String city2)
	{
		setCity2(getContext(), city2);
	}

	/**
	 * Set value of City2
	 * @param context
	 * @param city2
	 */
	public final void setCity2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city2)
	{
		getMendixObject().setValue(context, MemberNames.City2.toString(), city2);
	}

	/**
	 * @return value of Tel_number
	 */
	public final java.lang.String getTel_number()
	{
		return getTel_number(getContext());
	}

	/**
	 * @param context
	 * @return value of Tel_number
	 */
	public final java.lang.String getTel_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tel_number.toString());
	}

	/**
	 * Set value of Tel_number
	 * @param tel_number
	 */
	public final void setTel_number(java.lang.String tel_number)
	{
		setTel_number(getContext(), tel_number);
	}

	/**
	 * Set value of Tel_number
	 * @param context
	 * @param tel_number
	 */
	public final void setTel_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tel_number)
	{
		getMendixObject().setValue(context, MemberNames.Tel_number.toString(), tel_number);
	}

	/**
	 * @return value of Smtp_addr
	 */
	public final java.lang.String getSmtp_addr()
	{
		return getSmtp_addr(getContext());
	}

	/**
	 * @param context
	 * @return value of Smtp_addr
	 */
	public final java.lang.String getSmtp_addr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Smtp_addr.toString());
	}

	/**
	 * Set value of Smtp_addr
	 * @param smtp_addr
	 */
	public final void setSmtp_addr(java.lang.String smtp_addr)
	{
		setSmtp_addr(getContext(), smtp_addr);
	}

	/**
	 * Set value of Smtp_addr
	 * @param context
	 * @param smtp_addr
	 */
	public final void setSmtp_addr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String smtp_addr)
	{
		getMendixObject().setValue(context, MemberNames.Smtp_addr.toString(), smtp_addr);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Bukrs
	 */
	public final java.lang.String getBukrs()
	{
		return getBukrs(getContext());
	}

	/**
	 * @param context
	 * @return value of Bukrs
	 */
	public final java.lang.String getBukrs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bukrs.toString());
	}

	/**
	 * Set value of Bukrs
	 * @param bukrs
	 */
	public final void setBukrs(java.lang.String bukrs)
	{
		setBukrs(getContext(), bukrs);
	}

	/**
	 * Set value of Bukrs
	 * @param context
	 * @param bukrs
	 */
	public final void setBukrs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bukrs)
	{
		getMendixObject().setValue(context, MemberNames.Bukrs.toString(), bukrs);
	}

	/**
	 * @return value of Akont
	 */
	public final java.lang.String getAkont()
	{
		return getAkont(getContext());
	}

	/**
	 * @param context
	 * @return value of Akont
	 */
	public final java.lang.String getAkont(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Akont.toString());
	}

	/**
	 * Set value of Akont
	 * @param akont
	 */
	public final void setAkont(java.lang.String akont)
	{
		setAkont(getContext(), akont);
	}

	/**
	 * Set value of Akont
	 * @param context
	 * @param akont
	 */
	public final void setAkont(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String akont)
	{
		getMendixObject().setValue(context, MemberNames.Akont.toString(), akont);
	}

	/**
	 * @return value of Zterm
	 */
	public final java.lang.String getZterm()
	{
		return getZterm(getContext());
	}

	/**
	 * @param context
	 * @return value of Zterm
	 */
	public final java.lang.String getZterm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zterm.toString());
	}

	/**
	 * Set value of Zterm
	 * @param zterm
	 */
	public final void setZterm(java.lang.String zterm)
	{
		setZterm(getContext(), zterm);
	}

	/**
	 * Set value of Zterm
	 * @param context
	 * @param zterm
	 */
	public final void setZterm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zterm)
	{
		getMendixObject().setValue(context, MemberNames.Zterm.toString(), zterm);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Precisid
	 */
	public final java.lang.String getPrecisid()
	{
		return getPrecisid(getContext());
	}

	/**
	 * @param context
	 * @return value of Precisid
	 */
	public final java.lang.String getPrecisid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Precisid.toString());
	}

	/**
	 * Set value of Precisid
	 * @param precisid
	 */
	public final void setPrecisid(java.lang.String precisid)
	{
		setPrecisid(getContext(), precisid);
	}

	/**
	 * Set value of Precisid
	 * @param context
	 * @param precisid
	 */
	public final void setPrecisid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String precisid)
	{
		getMendixObject().setValue(context, MemberNames.Precisid.toString(), precisid);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final zgws_cust_get_srv.proxies.Customer that = (zgws_cust_get_srv.proxies.Customer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ZGWS_cust_GET_SRV.Customer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
