// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventmanagement.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the EventManagement module
	public static eventmanagement.proxies.Feedback createFeedback(IContext context, eventmanagement.proxies.Session _session)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Session", _session == null ? null : _session.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "EventManagement.CreateFeedback", params);
			return result == null ? null : eventmanagement.proxies.Feedback.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static eventmanagement.proxies.EventPhoto createPhoto(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "EventManagement.CreatePhoto", params);
			return result == null ? null : eventmanagement.proxies.EventPhoto.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void deletePhoto(IContext context, eventmanagement.proxies.EventPhoto _eventPhoto)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EventPhoto", _eventPhoto == null ? null : _eventPhoto.getMendixObject());
			Core.execute(context, "EventManagement.DeletePhoto", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static eventmanagement.proxies.AddressEntity getExampleAddress(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "EventManagement.GetExampleAddress", params);
			return result == null ? null : eventmanagement.proxies.AddressEntity.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void onSavePhoto(IContext context, eventmanagement.proxies.EventPhoto _eventPhoto)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EventPhoto", _eventPhoto == null ? null : _eventPhoto.getMendixObject());
			Core.execute(context, "EventManagement.OnSavePhoto", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void saveAttendee(IContext context, eventmanagement.proxies.Attendee _newAttendee)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NewAttendee", _newAttendee == null ? null : _newAttendee.getMendixObject());
			Core.execute(context, "EventManagement.SaveAttendee", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}