// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package trainingcourse.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TrainingCourse module
	public static void aCT_CancelSC(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			Core.execute(context, "TrainingCourse.ACT_CancelSC", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_CreateScheduledCourse(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "TrainingCourse.ACT_CreateScheduledCourse", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_DeleteSC(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			Core.execute(context, "TrainingCourse.ACT_DeleteSC", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_SaveSC(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			Core.execute(context, "TrainingCourse.ACT_SaveSC", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCT_ShowPage(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			Core.execute(context, "TrainingCourse.ACT_ShowPage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cALL_SAP(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "TrainingCourse.CALL_SAP", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cALL_SoapAPI(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "TrainingCourse.CALL_SoapAPI", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void course_Delete(IContext context, java.lang.String _title, system.proxies.HttpResponse _httpResponse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("title", _title);
			params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			Core.execute(context, "TrainingCourse.Course_Delete", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<trainingcourse.proxies.Course> course_Get_All(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "TrainingCourse.Course_Get_All", params);
			java.util.List<trainingcourse.proxies.Course> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<trainingcourse.proxies.Course>();
				for (IMendixObject obj : objs)
					result.add(trainingcourse.proxies.Course.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static trainingcourse.proxies.Course course_Get_ByKey(IContext context, system.proxies.HttpResponse _httpResponse, java.lang.String _title)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			params.put("title", _title);
			IMendixObject result = (IMendixObject)Core.execute(context, "TrainingCourse.Course_Get_ByKey", params);
			return result == null ? null : trainingcourse.proxies.Course.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void course_Patch(IContext context, trainingcourse.proxies.Course _body)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("body", _body == null ? null : _body.getMendixObject());
			Core.execute(context, "TrainingCourse.Course_Patch", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void course_Post(IContext context, system.proxies.HttpResponse _httpResponse, trainingcourse.proxies.Course _body)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			params.put("body", _body == null ? null : _body.getMendixObject());
			Core.execute(context, "TrainingCourse.Course_Post", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void eVH_CalculateNrOfRegistration(IContext context, trainingcourse.proxies.Registration _registration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Registration", _registration == null ? null : _registration.getMendixObject());
			Core.execute(context, "TrainingCourse.EVH_CalculateNrOfRegistration", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static trainingcourse.proxies.Dashboard gET_NrOfRegistration(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TrainingCourse.GET_NrOfRegistration", params);
			return result == null ? null : trainingcourse.proxies.Dashboard.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static trainingcourse.proxies.Weather gET_Weather(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TrainingCourse.GET_Weather", params);
			return result == null ? null : trainingcourse.proxies.Weather.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCH_CalculateEnddate(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			Core.execute(context, "TrainingCourse.OCH_CalculateEnddate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_ValidateSC(IContext context, trainingcourse.proxies.ScheduledCourse _scheduledCourse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ScheduledCourse", _scheduledCourse == null ? null : _scheduledCourse.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "TrainingCourse.SUB_ValidateSC", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static trainingcourse.proxies.Trainer wOP_GetTrainerByName(IContext context, java.lang.String _firstName)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("firstName", _firstName);
			IMendixObject result = (IMendixObject)Core.execute(context, "TrainingCourse.WOP_GetTrainerByName", params);
			return result == null ? null : trainingcourse.proxies.Trainer.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}