// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class DateRangeInput extends questionnaire.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.DateRangeInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Range("Range"),
		Date("Date"),
		ShowRangeValidation("ShowRangeValidation"),
		RangeValidationMessage("RangeValidationMessage"),
		Number("Number"),
		Sequence("Sequence"),
		Label("Label"),
		InputType("InputType"),
		RenderMode("RenderMode"),
		Required("Required"),
		ShowRequiredValidation("ShowRequiredValidation"),
		DisplayHelpText("DisplayHelpText"),
		HelpText("HelpText"),
		Visible("Visible"),
		SavedOnce("SavedOnce"),
		GraphCaptionNoSelection("GraphCaptionNoSelection"),
		DisplayNumber("DisplayNumber"),
		Element_Page("Questionnaire.Element_Page"),
		Element_ElementConfig("Questionnaire.Element_ElementConfig"),
		Element_Option_Selections("Questionnaire.Element_Option_Selections"),
		Element_Option_Selection("Questionnaire.Element_Option_Selection");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DateRangeInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.DateRangeInput"));
	}

	protected DateRangeInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dateRangeInputMendixObject)
	{
		super(context, dateRangeInputMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.DateRangeInput", dateRangeInputMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.DateRangeInput");
	}

	/**
	 * @deprecated Use 'DateRangeInput.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.DateRangeInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.DateRangeInput.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.DateRangeInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.DateRangeInput(context, mendixObject);
	}

	public static questionnaire.proxies.DateRangeInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.DateRangeInput.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.DateRangeInput> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.DateRangeInput> result = new java.util.ArrayList<questionnaire.proxies.DateRangeInput>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.DateRangeInput" + xpathConstraint))
			result.add(questionnaire.proxies.DateRangeInput.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of Range
	 * @param range
	 */
	public final questionnaire.proxies.DateRange getRange()
	{
		return getRange(getContext());
	}

	/**
	 * @param context
	 * @return value of Range
	 */
	public final questionnaire.proxies.DateRange getRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Range.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.DateRange.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Range
	 * @param range
	 */
	public final void setRange(questionnaire.proxies.DateRange range)
	{
		setRange(getContext(), range);
	}

	/**
	 * Set value of Range
	 * @param context
	 * @param range
	 */
	public final void setRange(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.DateRange range)
	{
		if (range != null)
			getMendixObject().setValue(context, MemberNames.Range.toString(), range.toString());
		else
			getMendixObject().setValue(context, MemberNames.Range.toString(), null);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of ShowRangeValidation
	 */
	public final java.lang.Boolean getShowRangeValidation()
	{
		return getShowRangeValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowRangeValidation
	 */
	public final java.lang.Boolean getShowRangeValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowRangeValidation.toString());
	}

	/**
	 * Set value of ShowRangeValidation
	 * @param showrangevalidation
	 */
	public final void setShowRangeValidation(java.lang.Boolean showrangevalidation)
	{
		setShowRangeValidation(getContext(), showrangevalidation);
	}

	/**
	 * Set value of ShowRangeValidation
	 * @param context
	 * @param showrangevalidation
	 */
	public final void setShowRangeValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showrangevalidation)
	{
		getMendixObject().setValue(context, MemberNames.ShowRangeValidation.toString(), showrangevalidation);
	}

	/**
	 * @return value of RangeValidationMessage
	 */
	public final java.lang.String getRangeValidationMessage()
	{
		return getRangeValidationMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of RangeValidationMessage
	 */
	public final java.lang.String getRangeValidationMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RangeValidationMessage.toString());
	}

	/**
	 * Set value of RangeValidationMessage
	 * @param rangevalidationmessage
	 */
	public final void setRangeValidationMessage(java.lang.String rangevalidationmessage)
	{
		setRangeValidationMessage(getContext(), rangevalidationmessage);
	}

	/**
	 * Set value of RangeValidationMessage
	 * @param context
	 * @param rangevalidationmessage
	 */
	public final void setRangeValidationMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rangevalidationmessage)
	{
		getMendixObject().setValue(context, MemberNames.RangeValidationMessage.toString(), rangevalidationmessage);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.DateRangeInput that = (questionnaire.proxies.DateRangeInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.DateRangeInput";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
