// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class DependencyConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dependencyConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.DependencyConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Expression("Expression"),
		ConfirmedAction("ConfirmedAction"),
		DependencyConfig_OptionConfig_OR("Questionnaire.DependencyConfig_OptionConfig_OR"),
		DependencyConfig_ElementConfig_OR("Questionnaire.DependencyConfig_ElementConfig_OR"),
		DependencyConfig_OptionConfig_AND("Questionnaire.DependencyConfig_OptionConfig_AND"),
		DependencyConfig_ElementConfig_Selectable("Questionnaire.DependencyConfig_ElementConfig_Selectable");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DependencyConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.DependencyConfig"));
	}

	protected DependencyConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dependencyConfigMendixObject)
	{
		if (dependencyConfigMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.DependencyConfig", dependencyConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.DependencyConfig");

		this.dependencyConfigMendixObject = dependencyConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DependencyConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.DependencyConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.DependencyConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.DependencyConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.DependencyConfig(context, mendixObject);
	}

	public static questionnaire.proxies.DependencyConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.DependencyConfig.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.DependencyConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.DependencyConfig> result = new java.util.ArrayList<questionnaire.proxies.DependencyConfig>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.DependencyConfig" + xpathConstraint))
			result.add(questionnaire.proxies.DependencyConfig.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Expression
	 */
	public final java.lang.String getExpression()
	{
		return getExpression(getContext());
	}

	/**
	 * @param context
	 * @return value of Expression
	 */
	public final java.lang.String getExpression(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Expression.toString());
	}

	/**
	 * Set value of Expression
	 * @param expression
	 */
	public final void setExpression(java.lang.String expression)
	{
		setExpression(getContext(), expression);
	}

	/**
	 * Set value of Expression
	 * @param context
	 * @param expression
	 */
	public final void setExpression(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expression)
	{
		getMendixObject().setValue(context, MemberNames.Expression.toString(), expression);
	}

	/**
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction()
	{
		return getConfirmedAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ConfirmedAction.toString());
	}

	/**
	 * Set value of ConfirmedAction
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(java.lang.Boolean confirmedaction)
	{
		setConfirmedAction(getContext(), confirmedaction);
	}

	/**
	 * Set value of ConfirmedAction
	 * @param context
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean confirmedaction)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmedAction.toString(), confirmedaction);
	}

	/**
	 * @return value of DependencyConfig_OptionConfig_OR
	 */
	public final questionnaire.proxies.OptionConfig getDependencyConfig_OptionConfig_OR() throws com.mendix.core.CoreException
	{
		return getDependencyConfig_OptionConfig_OR(getContext());
	}

	/**
	 * @param context
	 * @return value of DependencyConfig_OptionConfig_OR
	 */
	public final questionnaire.proxies.OptionConfig getDependencyConfig_OptionConfig_OR(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.OptionConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DependencyConfig_OptionConfig_OR.toString());
		if (identifier != null)
			result = questionnaire.proxies.OptionConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DependencyConfig_OptionConfig_OR
	 * @param dependencyconfig_optionconfig_or
	 */
	public final void setDependencyConfig_OptionConfig_OR(questionnaire.proxies.OptionConfig dependencyconfig_optionconfig_or)
	{
		setDependencyConfig_OptionConfig_OR(getContext(), dependencyconfig_optionconfig_or);
	}

	/**
	 * Set value of DependencyConfig_OptionConfig_OR
	 * @param context
	 * @param dependencyconfig_optionconfig_or
	 */
	public final void setDependencyConfig_OptionConfig_OR(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.OptionConfig dependencyconfig_optionconfig_or)
	{
		if (dependencyconfig_optionconfig_or == null)
			getMendixObject().setValue(context, MemberNames.DependencyConfig_OptionConfig_OR.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DependencyConfig_OptionConfig_OR.toString(), dependencyconfig_optionconfig_or.getMendixObject().getId());
	}

	/**
	 * @return value of DependencyConfig_ElementConfig_OR
	 */
	public final questionnaire.proxies.ElementConfig getDependencyConfig_ElementConfig_OR() throws com.mendix.core.CoreException
	{
		return getDependencyConfig_ElementConfig_OR(getContext());
	}

	/**
	 * @param context
	 * @return value of DependencyConfig_ElementConfig_OR
	 */
	public final questionnaire.proxies.ElementConfig getDependencyConfig_ElementConfig_OR(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.ElementConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DependencyConfig_ElementConfig_OR.toString());
		if (identifier != null)
			result = questionnaire.proxies.ElementConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DependencyConfig_ElementConfig_OR
	 * @param dependencyconfig_elementconfig_or
	 */
	public final void setDependencyConfig_ElementConfig_OR(questionnaire.proxies.ElementConfig dependencyconfig_elementconfig_or)
	{
		setDependencyConfig_ElementConfig_OR(getContext(), dependencyconfig_elementconfig_or);
	}

	/**
	 * Set value of DependencyConfig_ElementConfig_OR
	 * @param context
	 * @param dependencyconfig_elementconfig_or
	 */
	public final void setDependencyConfig_ElementConfig_OR(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.ElementConfig dependencyconfig_elementconfig_or)
	{
		if (dependencyconfig_elementconfig_or == null)
			getMendixObject().setValue(context, MemberNames.DependencyConfig_ElementConfig_OR.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DependencyConfig_ElementConfig_OR.toString(), dependencyconfig_elementconfig_or.getMendixObject().getId());
	}

	/**
	 * @return value of DependencyConfig_OptionConfig_AND
	 */
	public final java.util.List<questionnaire.proxies.OptionConfig> getDependencyConfig_OptionConfig_AND() throws com.mendix.core.CoreException
	{
		return getDependencyConfig_OptionConfig_AND(getContext());
	}

	/**
	 * @param context
	 * @return value of DependencyConfig_OptionConfig_AND
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<questionnaire.proxies.OptionConfig> getDependencyConfig_OptionConfig_AND(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.OptionConfig> result = new java.util.ArrayList<questionnaire.proxies.OptionConfig>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DependencyConfig_OptionConfig_AND.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(questionnaire.proxies.OptionConfig.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DependencyConfig_OptionConfig_AND
	 * @param dependencyconfig_optionconfig_and
	 */
	public final void setDependencyConfig_OptionConfig_AND(java.util.List<questionnaire.proxies.OptionConfig> dependencyconfig_optionconfig_and)
	{
		setDependencyConfig_OptionConfig_AND(getContext(), dependencyconfig_optionconfig_and);
	}

	/**
	 * Set value of DependencyConfig_OptionConfig_AND
	 * @param context
	 * @param dependencyconfig_optionconfig_and
	 */
	public final void setDependencyConfig_OptionConfig_AND(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<questionnaire.proxies.OptionConfig> dependencyconfig_optionconfig_and)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (questionnaire.proxies.OptionConfig proxyObject : dependencyconfig_optionconfig_and)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DependencyConfig_OptionConfig_AND.toString(), identifiers);
	}

	/**
	 * @return value of DependencyConfig_ElementConfig_Selectable
	 */
	public final java.util.List<questionnaire.proxies.ElementConfig> getDependencyConfig_ElementConfig_Selectable() throws com.mendix.core.CoreException
	{
		return getDependencyConfig_ElementConfig_Selectable(getContext());
	}

	/**
	 * @param context
	 * @return value of DependencyConfig_ElementConfig_Selectable
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<questionnaire.proxies.ElementConfig> getDependencyConfig_ElementConfig_Selectable(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.ElementConfig> result = new java.util.ArrayList<questionnaire.proxies.ElementConfig>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DependencyConfig_ElementConfig_Selectable.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(questionnaire.proxies.ElementConfig.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DependencyConfig_ElementConfig_Selectable
	 * @param dependencyconfig_elementconfig_selectable
	 */
	public final void setDependencyConfig_ElementConfig_Selectable(java.util.List<questionnaire.proxies.ElementConfig> dependencyconfig_elementconfig_selectable)
	{
		setDependencyConfig_ElementConfig_Selectable(getContext(), dependencyconfig_elementconfig_selectable);
	}

	/**
	 * Set value of DependencyConfig_ElementConfig_Selectable
	 * @param context
	 * @param dependencyconfig_elementconfig_selectable
	 */
	public final void setDependencyConfig_ElementConfig_Selectable(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<questionnaire.proxies.ElementConfig> dependencyconfig_elementconfig_selectable)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (questionnaire.proxies.ElementConfig proxyObject : dependencyconfig_elementconfig_selectable)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DependencyConfig_ElementConfig_Selectable.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dependencyConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.DependencyConfig that = (questionnaire.proxies.DependencyConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.DependencyConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
