// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class Element
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject elementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.Element";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Sequence("Sequence"),
		Label("Label"),
		InputType("InputType"),
		RenderMode("RenderMode"),
		Required("Required"),
		ShowRequiredValidation("ShowRequiredValidation"),
		DisplayHelpText("DisplayHelpText"),
		HelpText("HelpText"),
		Visible("Visible"),
		SavedOnce("SavedOnce"),
		GraphCaptionNoSelection("GraphCaptionNoSelection"),
		DisplayNumber("DisplayNumber"),
		Element_Page("Questionnaire.Element_Page"),
		Element_ElementConfig("Questionnaire.Element_ElementConfig"),
		Element_Option_Selections("Questionnaire.Element_Option_Selections"),
		Element_Option_Selection("Questionnaire.Element_Option_Selection");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Element(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.Element"));
	}

	protected Element(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject elementMendixObject)
	{
		if (elementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.Element", elementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.Element");

		this.elementMendixObject = elementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Element.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.Element initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.Element.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.Element initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Questionnaire.DateRangeInput", mendixObject.getType()))
			return questionnaire.proxies.DateRangeInput.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.ListInput", mendixObject.getType()))
			return questionnaire.proxies.ListInput.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.NumberRangeInput", mendixObject.getType()))
			return questionnaire.proxies.NumberRangeInput.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.TextInput", mendixObject.getType()))
			return questionnaire.proxies.TextInput.initialize(context, mendixObject);

		return new questionnaire.proxies.Element(context, mendixObject);
	}

	public static questionnaire.proxies.Element load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.Element.initialize(context, mendixObject);
	}

	public static java.util.List<? extends questionnaire.proxies.Element> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.Element> result = new java.util.ArrayList<questionnaire.proxies.Element>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.Element" + xpathConstraint))
			result.add(questionnaire.proxies.Element.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * Set value of InputType
	 * @param inputtype
	 */
	public final questionnaire.proxies.InputType getInputType()
	{
		return getInputType(getContext());
	}

	/**
	 * @param context
	 * @return value of InputType
	 */
	public final questionnaire.proxies.InputType getInputType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InputType.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.InputType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InputType
	 * @param inputtype
	 */
	public final void setInputType(questionnaire.proxies.InputType inputtype)
	{
		setInputType(getContext(), inputtype);
	}

	/**
	 * Set value of InputType
	 * @param context
	 * @param inputtype
	 */
	public final void setInputType(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.InputType inputtype)
	{
		if (inputtype != null)
			getMendixObject().setValue(context, MemberNames.InputType.toString(), inputtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.InputType.toString(), null);
	}

	/**
	 * Set value of RenderMode
	 * @param rendermode
	 */
	public final questionnaire.proxies.RenderMode getRenderMode()
	{
		return getRenderMode(getContext());
	}

	/**
	 * @param context
	 * @return value of RenderMode
	 */
	public final questionnaire.proxies.RenderMode getRenderMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RenderMode.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.RenderMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RenderMode
	 * @param rendermode
	 */
	public final void setRenderMode(questionnaire.proxies.RenderMode rendermode)
	{
		setRenderMode(getContext(), rendermode);
	}

	/**
	 * Set value of RenderMode
	 * @param context
	 * @param rendermode
	 */
	public final void setRenderMode(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.RenderMode rendermode)
	{
		if (rendermode != null)
			getMendixObject().setValue(context, MemberNames.RenderMode.toString(), rendermode.toString());
		else
			getMendixObject().setValue(context, MemberNames.RenderMode.toString(), null);
	}

	/**
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired()
	{
		return getRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Required.toString());
	}

	/**
	 * Set value of Required
	 * @param required
	 */
	public final void setRequired(java.lang.Boolean required)
	{
		setRequired(getContext(), required);
	}

	/**
	 * Set value of Required
	 * @param context
	 * @param required
	 */
	public final void setRequired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean required)
	{
		getMendixObject().setValue(context, MemberNames.Required.toString(), required);
	}

	/**
	 * @return value of ShowRequiredValidation
	 */
	public final java.lang.Boolean getShowRequiredValidation()
	{
		return getShowRequiredValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowRequiredValidation
	 */
	public final java.lang.Boolean getShowRequiredValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowRequiredValidation.toString());
	}

	/**
	 * Set value of ShowRequiredValidation
	 * @param showrequiredvalidation
	 */
	public final void setShowRequiredValidation(java.lang.Boolean showrequiredvalidation)
	{
		setShowRequiredValidation(getContext(), showrequiredvalidation);
	}

	/**
	 * Set value of ShowRequiredValidation
	 * @param context
	 * @param showrequiredvalidation
	 */
	public final void setShowRequiredValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showrequiredvalidation)
	{
		getMendixObject().setValue(context, MemberNames.ShowRequiredValidation.toString(), showrequiredvalidation);
	}

	/**
	 * @return value of DisplayHelpText
	 */
	public final java.lang.Boolean getDisplayHelpText()
	{
		return getDisplayHelpText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayHelpText
	 */
	public final java.lang.Boolean getDisplayHelpText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DisplayHelpText.toString());
	}

	/**
	 * Set value of DisplayHelpText
	 * @param displayhelptext
	 */
	public final void setDisplayHelpText(java.lang.Boolean displayhelptext)
	{
		setDisplayHelpText(getContext(), displayhelptext);
	}

	/**
	 * Set value of DisplayHelpText
	 * @param context
	 * @param displayhelptext
	 */
	public final void setDisplayHelpText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean displayhelptext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayHelpText.toString(), displayhelptext);
	}

	/**
	 * @return value of HelpText
	 */
	public final java.lang.String getHelpText()
	{
		return getHelpText(getContext());
	}

	/**
	 * @param context
	 * @return value of HelpText
	 */
	public final java.lang.String getHelpText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HelpText.toString());
	}

	/**
	 * Set value of HelpText
	 * @param helptext
	 */
	public final void setHelpText(java.lang.String helptext)
	{
		setHelpText(getContext(), helptext);
	}

	/**
	 * Set value of HelpText
	 * @param context
	 * @param helptext
	 */
	public final void setHelpText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String helptext)
	{
		getMendixObject().setValue(context, MemberNames.HelpText.toString(), helptext);
	}

	/**
	 * @return value of Visible
	 */
	public final java.lang.Boolean getVisible()
	{
		return getVisible(getContext());
	}

	/**
	 * @param context
	 * @return value of Visible
	 */
	public final java.lang.Boolean getVisible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Visible.toString());
	}

	/**
	 * Set value of Visible
	 * @param visible
	 */
	public final void setVisible(java.lang.Boolean visible)
	{
		setVisible(getContext(), visible);
	}

	/**
	 * Set value of Visible
	 * @param context
	 * @param visible
	 */
	public final void setVisible(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean visible)
	{
		getMendixObject().setValue(context, MemberNames.Visible.toString(), visible);
	}

	/**
	 * @return value of SavedOnce
	 */
	public final java.lang.Boolean getSavedOnce()
	{
		return getSavedOnce(getContext());
	}

	/**
	 * @param context
	 * @return value of SavedOnce
	 */
	public final java.lang.Boolean getSavedOnce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SavedOnce.toString());
	}

	/**
	 * Set value of SavedOnce
	 * @param savedonce
	 */
	public final void setSavedOnce(java.lang.Boolean savedonce)
	{
		setSavedOnce(getContext(), savedonce);
	}

	/**
	 * Set value of SavedOnce
	 * @param context
	 * @param savedonce
	 */
	public final void setSavedOnce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean savedonce)
	{
		getMendixObject().setValue(context, MemberNames.SavedOnce.toString(), savedonce);
	}

	/**
	 * @return value of GraphCaptionNoSelection
	 */
	public final java.lang.String getGraphCaptionNoSelection()
	{
		return getGraphCaptionNoSelection(getContext());
	}

	/**
	 * @param context
	 * @return value of GraphCaptionNoSelection
	 */
	public final java.lang.String getGraphCaptionNoSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GraphCaptionNoSelection.toString());
	}

	/**
	 * Set value of GraphCaptionNoSelection
	 * @param graphcaptionnoselection
	 */
	public final void setGraphCaptionNoSelection(java.lang.String graphcaptionnoselection)
	{
		setGraphCaptionNoSelection(getContext(), graphcaptionnoselection);
	}

	/**
	 * Set value of GraphCaptionNoSelection
	 * @param context
	 * @param graphcaptionnoselection
	 */
	public final void setGraphCaptionNoSelection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String graphcaptionnoselection)
	{
		getMendixObject().setValue(context, MemberNames.GraphCaptionNoSelection.toString(), graphcaptionnoselection);
	}

	/**
	 * @return value of DisplayNumber
	 */
	public final java.lang.Integer getDisplayNumber()
	{
		return getDisplayNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayNumber
	 */
	public final java.lang.Integer getDisplayNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DisplayNumber.toString());
	}

	/**
	 * Set value of DisplayNumber
	 * @param displaynumber
	 */
	public final void setDisplayNumber(java.lang.Integer displaynumber)
	{
		setDisplayNumber(getContext(), displaynumber);
	}

	/**
	 * Set value of DisplayNumber
	 * @param context
	 * @param displaynumber
	 */
	public final void setDisplayNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer displaynumber)
	{
		getMendixObject().setValue(context, MemberNames.DisplayNumber.toString(), displaynumber);
	}

	/**
	 * @return value of Element_Page
	 */
	public final questionnaire.proxies.Page getElement_Page() throws com.mendix.core.CoreException
	{
		return getElement_Page(getContext());
	}

	/**
	 * @param context
	 * @return value of Element_Page
	 */
	public final questionnaire.proxies.Page getElement_Page(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.Page result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Element_Page.toString());
		if (identifier != null)
			result = questionnaire.proxies.Page.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Element_Page
	 * @param element_page
	 */
	public final void setElement_Page(questionnaire.proxies.Page element_page)
	{
		setElement_Page(getContext(), element_page);
	}

	/**
	 * Set value of Element_Page
	 * @param context
	 * @param element_page
	 */
	public final void setElement_Page(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Page element_page)
	{
		if (element_page == null)
			getMendixObject().setValue(context, MemberNames.Element_Page.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Element_Page.toString(), element_page.getMendixObject().getId());
	}

	/**
	 * @return value of Element_ElementConfig
	 */
	public final questionnaire.proxies.ElementConfig getElement_ElementConfig() throws com.mendix.core.CoreException
	{
		return getElement_ElementConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of Element_ElementConfig
	 */
	public final questionnaire.proxies.ElementConfig getElement_ElementConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.ElementConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Element_ElementConfig.toString());
		if (identifier != null)
			result = questionnaire.proxies.ElementConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Element_ElementConfig
	 * @param element_elementconfig
	 */
	public final void setElement_ElementConfig(questionnaire.proxies.ElementConfig element_elementconfig)
	{
		setElement_ElementConfig(getContext(), element_elementconfig);
	}

	/**
	 * Set value of Element_ElementConfig
	 * @param context
	 * @param element_elementconfig
	 */
	public final void setElement_ElementConfig(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.ElementConfig element_elementconfig)
	{
		if (element_elementconfig == null)
			getMendixObject().setValue(context, MemberNames.Element_ElementConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Element_ElementConfig.toString(), element_elementconfig.getMendixObject().getId());
	}

	/**
	 * @return value of Element_Option_Selections
	 */
	public final java.util.List<questionnaire.proxies.Option> getElement_Option_Selections() throws com.mendix.core.CoreException
	{
		return getElement_Option_Selections(getContext());
	}

	/**
	 * @param context
	 * @return value of Element_Option_Selections
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<questionnaire.proxies.Option> getElement_Option_Selections(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.Option> result = new java.util.ArrayList<questionnaire.proxies.Option>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Element_Option_Selections.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(questionnaire.proxies.Option.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Element_Option_Selections
	 * @param element_option_selections
	 */
	public final void setElement_Option_Selections(java.util.List<questionnaire.proxies.Option> element_option_selections)
	{
		setElement_Option_Selections(getContext(), element_option_selections);
	}

	/**
	 * Set value of Element_Option_Selections
	 * @param context
	 * @param element_option_selections
	 */
	public final void setElement_Option_Selections(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<questionnaire.proxies.Option> element_option_selections)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (questionnaire.proxies.Option proxyObject : element_option_selections)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Element_Option_Selections.toString(), identifiers);
	}

	/**
	 * @return value of Element_Option_Selection
	 */
	public final questionnaire.proxies.Option getElement_Option_Selection() throws com.mendix.core.CoreException
	{
		return getElement_Option_Selection(getContext());
	}

	/**
	 * @param context
	 * @return value of Element_Option_Selection
	 */
	public final questionnaire.proxies.Option getElement_Option_Selection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.Option result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Element_Option_Selection.toString());
		if (identifier != null)
			result = questionnaire.proxies.Option.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Element_Option_Selection
	 * @param element_option_selection
	 */
	public final void setElement_Option_Selection(questionnaire.proxies.Option element_option_selection)
	{
		setElement_Option_Selection(getContext(), element_option_selection);
	}

	/**
	 * Set value of Element_Option_Selection
	 * @param context
	 * @param element_option_selection
	 */
	public final void setElement_Option_Selection(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Option element_option_selection)
	{
		if (element_option_selection == null)
			getMendixObject().setValue(context, MemberNames.Element_Option_Selection.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Element_Option_Selection.toString(), element_option_selection.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return elementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.Element that = (questionnaire.proxies.Element) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.Element";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
