// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class ElementConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject elementConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.ElementConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		UpdateSequenceType("UpdateSequenceType"),
		ConfirmedAction("ConfirmedAction"),
		LabelHTML("LabelHTML"),
		LabelPlainText("LabelPlainText"),
		DisplayHelpText("DisplayHelpText"),
		HelpText("HelpText"),
		Visibility("Visibility"),
		ElementConfigType("ElementConfigType"),
		Score("Score"),
		ElementConfig_QuestionnaireConfig("Questionnaire.ElementConfig_QuestionnaireConfig"),
		ElementConfig_ElementConfig_CreatedFrom("Questionnaire.ElementConfig_ElementConfig_CreatedFrom");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ElementConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.ElementConfig"));
	}

	protected ElementConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject elementConfigMendixObject)
	{
		if (elementConfigMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.ElementConfig", elementConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.ElementConfig");

		this.elementConfigMendixObject = elementConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ElementConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.ElementConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.ElementConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.ElementConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Questionnaire.DateRangeInputConfig", mendixObject.getType()))
			return questionnaire.proxies.DateRangeInputConfig.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.ListInputConfig", mendixObject.getType()))
			return questionnaire.proxies.ListInputConfig.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.NumberRangeInputConfig", mendixObject.getType()))
			return questionnaire.proxies.NumberRangeInputConfig.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Questionnaire.TextInputConfig", mendixObject.getType()))
			return questionnaire.proxies.TextInputConfig.initialize(context, mendixObject);

		return new questionnaire.proxies.ElementConfig(context, mendixObject);
	}

	public static questionnaire.proxies.ElementConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.ElementConfig.initialize(context, mendixObject);
	}

	public static java.util.List<? extends questionnaire.proxies.ElementConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.ElementConfig> result = new java.util.ArrayList<questionnaire.proxies.ElementConfig>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.ElementConfig" + xpathConstraint))
			result.add(questionnaire.proxies.ElementConfig.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * Set value of UpdateSequenceType
	 * @param updatesequencetype
	 */
	public final questionnaire.proxies.UpdateSequenceType getUpdateSequenceType()
	{
		return getUpdateSequenceType(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdateSequenceType
	 */
	public final questionnaire.proxies.UpdateSequenceType getUpdateSequenceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UpdateSequenceType.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.UpdateSequenceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UpdateSequenceType
	 * @param updatesequencetype
	 */
	public final void setUpdateSequenceType(questionnaire.proxies.UpdateSequenceType updatesequencetype)
	{
		setUpdateSequenceType(getContext(), updatesequencetype);
	}

	/**
	 * Set value of UpdateSequenceType
	 * @param context
	 * @param updatesequencetype
	 */
	public final void setUpdateSequenceType(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.UpdateSequenceType updatesequencetype)
	{
		if (updatesequencetype != null)
			getMendixObject().setValue(context, MemberNames.UpdateSequenceType.toString(), updatesequencetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.UpdateSequenceType.toString(), null);
	}

	/**
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction()
	{
		return getConfirmedAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ConfirmedAction.toString());
	}

	/**
	 * Set value of ConfirmedAction
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(java.lang.Boolean confirmedaction)
	{
		setConfirmedAction(getContext(), confirmedaction);
	}

	/**
	 * Set value of ConfirmedAction
	 * @param context
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean confirmedaction)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmedAction.toString(), confirmedaction);
	}

	/**
	 * @return value of LabelHTML
	 */
	public final java.lang.String getLabelHTML()
	{
		return getLabelHTML(getContext());
	}

	/**
	 * @param context
	 * @return value of LabelHTML
	 */
	public final java.lang.String getLabelHTML(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LabelHTML.toString());
	}

	/**
	 * Set value of LabelHTML
	 * @param labelhtml
	 */
	public final void setLabelHTML(java.lang.String labelhtml)
	{
		setLabelHTML(getContext(), labelhtml);
	}

	/**
	 * Set value of LabelHTML
	 * @param context
	 * @param labelhtml
	 */
	public final void setLabelHTML(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String labelhtml)
	{
		getMendixObject().setValue(context, MemberNames.LabelHTML.toString(), labelhtml);
	}

	/**
	 * @return value of LabelPlainText
	 */
	public final java.lang.String getLabelPlainText()
	{
		return getLabelPlainText(getContext());
	}

	/**
	 * @param context
	 * @return value of LabelPlainText
	 */
	public final java.lang.String getLabelPlainText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LabelPlainText.toString());
	}

	/**
	 * Set value of LabelPlainText
	 * @param labelplaintext
	 */
	public final void setLabelPlainText(java.lang.String labelplaintext)
	{
		setLabelPlainText(getContext(), labelplaintext);
	}

	/**
	 * Set value of LabelPlainText
	 * @param context
	 * @param labelplaintext
	 */
	public final void setLabelPlainText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String labelplaintext)
	{
		getMendixObject().setValue(context, MemberNames.LabelPlainText.toString(), labelplaintext);
	}

	/**
	 * @return value of DisplayHelpText
	 */
	public final java.lang.Boolean getDisplayHelpText()
	{
		return getDisplayHelpText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayHelpText
	 */
	public final java.lang.Boolean getDisplayHelpText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DisplayHelpText.toString());
	}

	/**
	 * Set value of DisplayHelpText
	 * @param displayhelptext
	 */
	public final void setDisplayHelpText(java.lang.Boolean displayhelptext)
	{
		setDisplayHelpText(getContext(), displayhelptext);
	}

	/**
	 * Set value of DisplayHelpText
	 * @param context
	 * @param displayhelptext
	 */
	public final void setDisplayHelpText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean displayhelptext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayHelpText.toString(), displayhelptext);
	}

	/**
	 * @return value of HelpText
	 */
	public final java.lang.String getHelpText()
	{
		return getHelpText(getContext());
	}

	/**
	 * @param context
	 * @return value of HelpText
	 */
	public final java.lang.String getHelpText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HelpText.toString());
	}

	/**
	 * Set value of HelpText
	 * @param helptext
	 */
	public final void setHelpText(java.lang.String helptext)
	{
		setHelpText(getContext(), helptext);
	}

	/**
	 * Set value of HelpText
	 * @param context
	 * @param helptext
	 */
	public final void setHelpText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String helptext)
	{
		getMendixObject().setValue(context, MemberNames.HelpText.toString(), helptext);
	}

	/**
	 * Set value of Visibility
	 * @param visibility
	 */
	public final questionnaire.proxies.Visibility getVisibility()
	{
		return getVisibility(getContext());
	}

	/**
	 * @param context
	 * @return value of Visibility
	 */
	public final questionnaire.proxies.Visibility getVisibility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Visibility.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.Visibility.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Visibility
	 * @param visibility
	 */
	public final void setVisibility(questionnaire.proxies.Visibility visibility)
	{
		setVisibility(getContext(), visibility);
	}

	/**
	 * Set value of Visibility
	 * @param context
	 * @param visibility
	 */
	public final void setVisibility(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Visibility visibility)
	{
		if (visibility != null)
			getMendixObject().setValue(context, MemberNames.Visibility.toString(), visibility.toString());
		else
			getMendixObject().setValue(context, MemberNames.Visibility.toString(), null);
	}

	/**
	 * Set value of ElementConfigType
	 * @param elementconfigtype
	 */
	public final questionnaire.proxies.ElementConfigType getElementConfigType()
	{
		return getElementConfigType(getContext());
	}

	/**
	 * @param context
	 * @return value of ElementConfigType
	 */
	public final questionnaire.proxies.ElementConfigType getElementConfigType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ElementConfigType.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.ElementConfigType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ElementConfigType
	 * @param elementconfigtype
	 */
	public final void setElementConfigType(questionnaire.proxies.ElementConfigType elementconfigtype)
	{
		setElementConfigType(getContext(), elementconfigtype);
	}

	/**
	 * Set value of ElementConfigType
	 * @param context
	 * @param elementconfigtype
	 */
	public final void setElementConfigType(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.ElementConfigType elementconfigtype)
	{
		if (elementconfigtype != null)
			getMendixObject().setValue(context, MemberNames.ElementConfigType.toString(), elementconfigtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ElementConfigType.toString(), null);
	}

	/**
	 * @return value of Score
	 */
	public final java.lang.Integer getScore()
	{
		return getScore(getContext());
	}

	/**
	 * @param context
	 * @return value of Score
	 */
	public final java.lang.Integer getScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Score.toString());
	}

	/**
	 * Set value of Score
	 * @param score
	 */
	public final void setScore(java.lang.Integer score)
	{
		setScore(getContext(), score);
	}

	/**
	 * Set value of Score
	 * @param context
	 * @param score
	 */
	public final void setScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer score)
	{
		getMendixObject().setValue(context, MemberNames.Score.toString(), score);
	}

	/**
	 * @return value of ElementConfig_QuestionnaireConfig
	 */
	public final questionnaire.proxies.QuestionnaireConfig getElementConfig_QuestionnaireConfig() throws com.mendix.core.CoreException
	{
		return getElementConfig_QuestionnaireConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of ElementConfig_QuestionnaireConfig
	 */
	public final questionnaire.proxies.QuestionnaireConfig getElementConfig_QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.QuestionnaireConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ElementConfig_QuestionnaireConfig.toString());
		if (identifier != null)
			result = questionnaire.proxies.QuestionnaireConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ElementConfig_QuestionnaireConfig
	 * @param elementconfig_questionnaireconfig
	 */
	public final void setElementConfig_QuestionnaireConfig(questionnaire.proxies.QuestionnaireConfig elementconfig_questionnaireconfig)
	{
		setElementConfig_QuestionnaireConfig(getContext(), elementconfig_questionnaireconfig);
	}

	/**
	 * Set value of ElementConfig_QuestionnaireConfig
	 * @param context
	 * @param elementconfig_questionnaireconfig
	 */
	public final void setElementConfig_QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.QuestionnaireConfig elementconfig_questionnaireconfig)
	{
		if (elementconfig_questionnaireconfig == null)
			getMendixObject().setValue(context, MemberNames.ElementConfig_QuestionnaireConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ElementConfig_QuestionnaireConfig.toString(), elementconfig_questionnaireconfig.getMendixObject().getId());
	}

	/**
	 * @return value of ElementConfig_ElementConfig_CreatedFrom
	 */
	public final questionnaire.proxies.ElementConfig getElementConfig_ElementConfig_CreatedFrom() throws com.mendix.core.CoreException
	{
		return getElementConfig_ElementConfig_CreatedFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of ElementConfig_ElementConfig_CreatedFrom
	 */
	public final questionnaire.proxies.ElementConfig getElementConfig_ElementConfig_CreatedFrom(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.ElementConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ElementConfig_ElementConfig_CreatedFrom.toString());
		if (identifier != null)
			result = questionnaire.proxies.ElementConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ElementConfig_ElementConfig_CreatedFrom
	 * @param elementconfig_elementconfig_createdfrom
	 */
	public final void setElementConfig_ElementConfig_CreatedFrom(questionnaire.proxies.ElementConfig elementconfig_elementconfig_createdfrom)
	{
		setElementConfig_ElementConfig_CreatedFrom(getContext(), elementconfig_elementconfig_createdfrom);
	}

	/**
	 * Set value of ElementConfig_ElementConfig_CreatedFrom
	 * @param context
	 * @param elementconfig_elementconfig_createdfrom
	 */
	public final void setElementConfig_ElementConfig_CreatedFrom(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.ElementConfig elementconfig_elementconfig_createdfrom)
	{
		if (elementconfig_elementconfig_createdfrom == null)
			getMendixObject().setValue(context, MemberNames.ElementConfig_ElementConfig_CreatedFrom.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ElementConfig_ElementConfig_CreatedFrom.toString(), elementconfig_elementconfig_createdfrom.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return elementConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.ElementConfig that = (questionnaire.proxies.ElementConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.ElementConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
