// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public enum InputType
{
	Date(new java.lang.String[][] { new java.lang.String[] { "en_US", "Date" } }),
	Text(new java.lang.String[][] { new java.lang.String[] { "en_US", "Text" } }),
	Selection(new java.lang.String[][] { new java.lang.String[] { "en_US", "Selection" } }),
	Selections(new java.lang.String[][] { new java.lang.String[] { "en_US", "Selections" } }),
	Decimal(new java.lang.String[][] { new java.lang.String[] { "en_US", "Decimal" } }),
	WholeNumber(new java.lang.String[][] { new java.lang.String[] { "en_US", "WholeNumber" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private InputType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
