// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class NumberRangeInput extends questionnaire.proxies.Element
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.NumberRangeInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Range("Range"),
		Decimal("Decimal"),
		WholeNumber("WholeNumber"),
		ShowRangeValidation("ShowRangeValidation"),
		RangeValidationMessage("RangeValidationMessage"),
		Number("Number"),
		Sequence("Sequence"),
		Label("Label"),
		InputType("InputType"),
		RenderMode("RenderMode"),
		Required("Required"),
		ShowRequiredValidation("ShowRequiredValidation"),
		DisplayHelpText("DisplayHelpText"),
		HelpText("HelpText"),
		Visible("Visible"),
		SavedOnce("SavedOnce"),
		GraphCaptionNoSelection("GraphCaptionNoSelection"),
		DisplayNumber("DisplayNumber"),
		Element_Page("Questionnaire.Element_Page"),
		Element_ElementConfig("Questionnaire.Element_ElementConfig"),
		Element_Option_Selections("Questionnaire.Element_Option_Selections"),
		Element_Option_Selection("Questionnaire.Element_Option_Selection");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NumberRangeInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.NumberRangeInput"));
	}

	protected NumberRangeInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject numberRangeInputMendixObject)
	{
		super(context, numberRangeInputMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.NumberRangeInput", numberRangeInputMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.NumberRangeInput");
	}

	/**
	 * @deprecated Use 'NumberRangeInput.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.NumberRangeInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.NumberRangeInput.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.NumberRangeInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.NumberRangeInput(context, mendixObject);
	}

	public static questionnaire.proxies.NumberRangeInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.NumberRangeInput.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.NumberRangeInput> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.NumberRangeInput> result = new java.util.ArrayList<questionnaire.proxies.NumberRangeInput>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.NumberRangeInput" + xpathConstraint))
			result.add(questionnaire.proxies.NumberRangeInput.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of Range
	 * @param range
	 */
	public final questionnaire.proxies.NumberRange getRange()
	{
		return getRange(getContext());
	}

	/**
	 * @param context
	 * @return value of Range
	 */
	public final questionnaire.proxies.NumberRange getRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Range.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.NumberRange.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Range
	 * @param range
	 */
	public final void setRange(questionnaire.proxies.NumberRange range)
	{
		setRange(getContext(), range);
	}

	/**
	 * Set value of Range
	 * @param context
	 * @param range
	 */
	public final void setRange(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.NumberRange range)
	{
		if (range != null)
			getMendixObject().setValue(context, MemberNames.Range.toString(), range.toString());
		else
			getMendixObject().setValue(context, MemberNames.Range.toString(), null);
	}

	/**
	 * @return value of Decimal
	 */
	public final java.lang.Double getDecimal()
	{
		return getDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Decimal
	 */
	public final java.lang.Double getDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Decimal.toString());
	}

	/**
	 * Set value of Decimal
	 * @param decimal
	 */
	public final void setDecimal(java.lang.Double decimal)
	{
		setDecimal(getContext(), decimal);
	}

	/**
	 * Set value of Decimal
	 * @param context
	 * @param decimal
	 */
	public final void setDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double decimal)
	{
		getMendixObject().setValue(context, MemberNames.Decimal.toString(), decimal);
	}

	/**
	 * @return value of WholeNumber
	 */
	public final java.lang.Integer getWholeNumber()
	{
		return getWholeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WholeNumber
	 */
	public final java.lang.Integer getWholeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WholeNumber.toString());
	}

	/**
	 * Set value of WholeNumber
	 * @param wholenumber
	 */
	public final void setWholeNumber(java.lang.Integer wholenumber)
	{
		setWholeNumber(getContext(), wholenumber);
	}

	/**
	 * Set value of WholeNumber
	 * @param context
	 * @param wholenumber
	 */
	public final void setWholeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer wholenumber)
	{
		getMendixObject().setValue(context, MemberNames.WholeNumber.toString(), wholenumber);
	}

	/**
	 * @return value of ShowRangeValidation
	 */
	public final java.lang.Boolean getShowRangeValidation()
	{
		return getShowRangeValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowRangeValidation
	 */
	public final java.lang.Boolean getShowRangeValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowRangeValidation.toString());
	}

	/**
	 * Set value of ShowRangeValidation
	 * @param showrangevalidation
	 */
	public final void setShowRangeValidation(java.lang.Boolean showrangevalidation)
	{
		setShowRangeValidation(getContext(), showrangevalidation);
	}

	/**
	 * Set value of ShowRangeValidation
	 * @param context
	 * @param showrangevalidation
	 */
	public final void setShowRangeValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showrangevalidation)
	{
		getMendixObject().setValue(context, MemberNames.ShowRangeValidation.toString(), showrangevalidation);
	}

	/**
	 * @return value of RangeValidationMessage
	 */
	public final java.lang.String getRangeValidationMessage()
	{
		return getRangeValidationMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of RangeValidationMessage
	 */
	public final java.lang.String getRangeValidationMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RangeValidationMessage.toString());
	}

	/**
	 * Set value of RangeValidationMessage
	 * @param rangevalidationmessage
	 */
	public final void setRangeValidationMessage(java.lang.String rangevalidationmessage)
	{
		setRangeValidationMessage(getContext(), rangevalidationmessage);
	}

	/**
	 * Set value of RangeValidationMessage
	 * @param context
	 * @param rangevalidationmessage
	 */
	public final void setRangeValidationMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rangevalidationmessage)
	{
		getMendixObject().setValue(context, MemberNames.RangeValidationMessage.toString(), rangevalidationmessage);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.NumberRangeInput that = (questionnaire.proxies.NumberRangeInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.NumberRangeInput";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
