// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class Option
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject optionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.Option";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		Label("Label"),
		StartNumberRange("StartNumberRange"),
		EndNumberRange("EndNumberRange"),
		StartDateRange("StartDateRange"),
		EndDateRange("EndDateRange"),
		Applicable("Applicable"),
		Option_Element_Selectable("Questionnaire.Option_Element_Selectable"),
		Option_OptionConfig("Questionnaire.Option_OptionConfig");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Option(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.Option"));
	}

	protected Option(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject optionMendixObject)
	{
		if (optionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.Option", optionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.Option");

		this.optionMendixObject = optionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Option.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.Option initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.Option.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.Option initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.Option(context, mendixObject);
	}

	public static questionnaire.proxies.Option load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.Option.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.Option> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.Option> result = new java.util.ArrayList<questionnaire.proxies.Option>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.Option" + xpathConstraint))
			result.add(questionnaire.proxies.Option.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of StartNumberRange
	 */
	public final java.lang.Double getStartNumberRange()
	{
		return getStartNumberRange(getContext());
	}

	/**
	 * @param context
	 * @return value of StartNumberRange
	 */
	public final java.lang.Double getStartNumberRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.StartNumberRange.toString());
	}

	/**
	 * Set value of StartNumberRange
	 * @param startnumberrange
	 */
	public final void setStartNumberRange(java.lang.Double startnumberrange)
	{
		setStartNumberRange(getContext(), startnumberrange);
	}

	/**
	 * Set value of StartNumberRange
	 * @param context
	 * @param startnumberrange
	 */
	public final void setStartNumberRange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double startnumberrange)
	{
		getMendixObject().setValue(context, MemberNames.StartNumberRange.toString(), startnumberrange);
	}

	/**
	 * @return value of EndNumberRange
	 */
	public final java.lang.Double getEndNumberRange()
	{
		return getEndNumberRange(getContext());
	}

	/**
	 * @param context
	 * @return value of EndNumberRange
	 */
	public final java.lang.Double getEndNumberRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.EndNumberRange.toString());
	}

	/**
	 * Set value of EndNumberRange
	 * @param endnumberrange
	 */
	public final void setEndNumberRange(java.lang.Double endnumberrange)
	{
		setEndNumberRange(getContext(), endnumberrange);
	}

	/**
	 * Set value of EndNumberRange
	 * @param context
	 * @param endnumberrange
	 */
	public final void setEndNumberRange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double endnumberrange)
	{
		getMendixObject().setValue(context, MemberNames.EndNumberRange.toString(), endnumberrange);
	}

	/**
	 * @return value of StartDateRange
	 */
	public final java.util.Date getStartDateRange()
	{
		return getStartDateRange(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateRange
	 */
	public final java.util.Date getStartDateRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDateRange.toString());
	}

	/**
	 * Set value of StartDateRange
	 * @param startdaterange
	 */
	public final void setStartDateRange(java.util.Date startdaterange)
	{
		setStartDateRange(getContext(), startdaterange);
	}

	/**
	 * Set value of StartDateRange
	 * @param context
	 * @param startdaterange
	 */
	public final void setStartDateRange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdaterange)
	{
		getMendixObject().setValue(context, MemberNames.StartDateRange.toString(), startdaterange);
	}

	/**
	 * @return value of EndDateRange
	 */
	public final java.util.Date getEndDateRange()
	{
		return getEndDateRange(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateRange
	 */
	public final java.util.Date getEndDateRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDateRange.toString());
	}

	/**
	 * Set value of EndDateRange
	 * @param enddaterange
	 */
	public final void setEndDateRange(java.util.Date enddaterange)
	{
		setEndDateRange(getContext(), enddaterange);
	}

	/**
	 * Set value of EndDateRange
	 * @param context
	 * @param enddaterange
	 */
	public final void setEndDateRange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddaterange)
	{
		getMendixObject().setValue(context, MemberNames.EndDateRange.toString(), enddaterange);
	}

	/**
	 * @return value of Applicable
	 */
	public final java.lang.Boolean getApplicable()
	{
		return getApplicable(getContext());
	}

	/**
	 * @param context
	 * @return value of Applicable
	 */
	public final java.lang.Boolean getApplicable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Applicable.toString());
	}

	/**
	 * Set value of Applicable
	 * @param applicable
	 */
	public final void setApplicable(java.lang.Boolean applicable)
	{
		setApplicable(getContext(), applicable);
	}

	/**
	 * Set value of Applicable
	 * @param context
	 * @param applicable
	 */
	public final void setApplicable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean applicable)
	{
		getMendixObject().setValue(context, MemberNames.Applicable.toString(), applicable);
	}

	/**
	 * @return value of Option_Element_Selectable
	 */
	public final questionnaire.proxies.Element getOption_Element_Selectable() throws com.mendix.core.CoreException
	{
		return getOption_Element_Selectable(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_Element_Selectable
	 */
	public final questionnaire.proxies.Element getOption_Element_Selectable(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.Element result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Option_Element_Selectable.toString());
		if (identifier != null)
			result = questionnaire.proxies.Element.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Option_Element_Selectable
	 * @param option_element_selectable
	 */
	public final void setOption_Element_Selectable(questionnaire.proxies.Element option_element_selectable)
	{
		setOption_Element_Selectable(getContext(), option_element_selectable);
	}

	/**
	 * Set value of Option_Element_Selectable
	 * @param context
	 * @param option_element_selectable
	 */
	public final void setOption_Element_Selectable(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Element option_element_selectable)
	{
		if (option_element_selectable == null)
			getMendixObject().setValue(context, MemberNames.Option_Element_Selectable.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Option_Element_Selectable.toString(), option_element_selectable.getMendixObject().getId());
	}

	/**
	 * @return value of Option_OptionConfig
	 */
	public final questionnaire.proxies.OptionConfig getOption_OptionConfig() throws com.mendix.core.CoreException
	{
		return getOption_OptionConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of Option_OptionConfig
	 */
	public final questionnaire.proxies.OptionConfig getOption_OptionConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.OptionConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Option_OptionConfig.toString());
		if (identifier != null)
			result = questionnaire.proxies.OptionConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Option_OptionConfig
	 * @param option_optionconfig
	 */
	public final void setOption_OptionConfig(questionnaire.proxies.OptionConfig option_optionconfig)
	{
		setOption_OptionConfig(getContext(), option_optionconfig);
	}

	/**
	 * Set value of Option_OptionConfig
	 * @param context
	 * @param option_optionconfig
	 */
	public final void setOption_OptionConfig(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.OptionConfig option_optionconfig)
	{
		if (option_optionconfig == null)
			getMendixObject().setValue(context, MemberNames.Option_OptionConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Option_OptionConfig.toString(), option_optionconfig.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return optionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.Option that = (questionnaire.proxies.Option) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.Option";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
