// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class PageNav
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pageNavMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.PageNav";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Page1Exists("Page1Exists"),
		Page1Active("Page1Active"),
		Page1Visited("Page1Visited"),
		Page2Exists("Page2Exists"),
		Page2Active("Page2Active"),
		Page2Visited("Page2Visited"),
		Page3Exists("Page3Exists"),
		Page4Exists("Page4Exists"),
		Page3Active("Page3Active"),
		Page3Visited("Page3Visited"),
		Page4Active("Page4Active"),
		Page4Visited("Page4Visited"),
		PageNav_Page("Questionnaire.PageNav_Page");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PageNav(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.PageNav"));
	}

	protected PageNav(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pageNavMendixObject)
	{
		if (pageNavMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.PageNav", pageNavMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.PageNav");

		this.pageNavMendixObject = pageNavMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PageNav.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.PageNav initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.PageNav.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.PageNav initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.PageNav(context, mendixObject);
	}

	public static questionnaire.proxies.PageNav load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.PageNav.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Page1Exists
	 */
	public final java.lang.Boolean getPage1Exists()
	{
		return getPage1Exists(getContext());
	}

	/**
	 * @param context
	 * @return value of Page1Exists
	 */
	public final java.lang.Boolean getPage1Exists(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page1Exists.toString());
	}

	/**
	 * Set value of Page1Exists
	 * @param page1exists
	 */
	public final void setPage1Exists(java.lang.Boolean page1exists)
	{
		setPage1Exists(getContext(), page1exists);
	}

	/**
	 * Set value of Page1Exists
	 * @param context
	 * @param page1exists
	 */
	public final void setPage1Exists(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page1exists)
	{
		getMendixObject().setValue(context, MemberNames.Page1Exists.toString(), page1exists);
	}

	/**
	 * @return value of Page1Active
	 */
	public final java.lang.Boolean getPage1Active()
	{
		return getPage1Active(getContext());
	}

	/**
	 * @param context
	 * @return value of Page1Active
	 */
	public final java.lang.Boolean getPage1Active(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page1Active.toString());
	}

	/**
	 * Set value of Page1Active
	 * @param page1active
	 */
	public final void setPage1Active(java.lang.Boolean page1active)
	{
		setPage1Active(getContext(), page1active);
	}

	/**
	 * Set value of Page1Active
	 * @param context
	 * @param page1active
	 */
	public final void setPage1Active(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page1active)
	{
		getMendixObject().setValue(context, MemberNames.Page1Active.toString(), page1active);
	}

	/**
	 * @return value of Page1Visited
	 */
	public final java.lang.Boolean getPage1Visited()
	{
		return getPage1Visited(getContext());
	}

	/**
	 * @param context
	 * @return value of Page1Visited
	 */
	public final java.lang.Boolean getPage1Visited(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page1Visited.toString());
	}

	/**
	 * Set value of Page1Visited
	 * @param page1visited
	 */
	public final void setPage1Visited(java.lang.Boolean page1visited)
	{
		setPage1Visited(getContext(), page1visited);
	}

	/**
	 * Set value of Page1Visited
	 * @param context
	 * @param page1visited
	 */
	public final void setPage1Visited(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page1visited)
	{
		getMendixObject().setValue(context, MemberNames.Page1Visited.toString(), page1visited);
	}

	/**
	 * @return value of Page2Exists
	 */
	public final java.lang.Boolean getPage2Exists()
	{
		return getPage2Exists(getContext());
	}

	/**
	 * @param context
	 * @return value of Page2Exists
	 */
	public final java.lang.Boolean getPage2Exists(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page2Exists.toString());
	}

	/**
	 * Set value of Page2Exists
	 * @param page2exists
	 */
	public final void setPage2Exists(java.lang.Boolean page2exists)
	{
		setPage2Exists(getContext(), page2exists);
	}

	/**
	 * Set value of Page2Exists
	 * @param context
	 * @param page2exists
	 */
	public final void setPage2Exists(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page2exists)
	{
		getMendixObject().setValue(context, MemberNames.Page2Exists.toString(), page2exists);
	}

	/**
	 * @return value of Page2Active
	 */
	public final java.lang.Boolean getPage2Active()
	{
		return getPage2Active(getContext());
	}

	/**
	 * @param context
	 * @return value of Page2Active
	 */
	public final java.lang.Boolean getPage2Active(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page2Active.toString());
	}

	/**
	 * Set value of Page2Active
	 * @param page2active
	 */
	public final void setPage2Active(java.lang.Boolean page2active)
	{
		setPage2Active(getContext(), page2active);
	}

	/**
	 * Set value of Page2Active
	 * @param context
	 * @param page2active
	 */
	public final void setPage2Active(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page2active)
	{
		getMendixObject().setValue(context, MemberNames.Page2Active.toString(), page2active);
	}

	/**
	 * @return value of Page2Visited
	 */
	public final java.lang.Boolean getPage2Visited()
	{
		return getPage2Visited(getContext());
	}

	/**
	 * @param context
	 * @return value of Page2Visited
	 */
	public final java.lang.Boolean getPage2Visited(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page2Visited.toString());
	}

	/**
	 * Set value of Page2Visited
	 * @param page2visited
	 */
	public final void setPage2Visited(java.lang.Boolean page2visited)
	{
		setPage2Visited(getContext(), page2visited);
	}

	/**
	 * Set value of Page2Visited
	 * @param context
	 * @param page2visited
	 */
	public final void setPage2Visited(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page2visited)
	{
		getMendixObject().setValue(context, MemberNames.Page2Visited.toString(), page2visited);
	}

	/**
	 * @return value of Page3Exists
	 */
	public final java.lang.Boolean getPage3Exists()
	{
		return getPage3Exists(getContext());
	}

	/**
	 * @param context
	 * @return value of Page3Exists
	 */
	public final java.lang.Boolean getPage3Exists(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page3Exists.toString());
	}

	/**
	 * Set value of Page3Exists
	 * @param page3exists
	 */
	public final void setPage3Exists(java.lang.Boolean page3exists)
	{
		setPage3Exists(getContext(), page3exists);
	}

	/**
	 * Set value of Page3Exists
	 * @param context
	 * @param page3exists
	 */
	public final void setPage3Exists(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page3exists)
	{
		getMendixObject().setValue(context, MemberNames.Page3Exists.toString(), page3exists);
	}

	/**
	 * @return value of Page4Exists
	 */
	public final java.lang.Boolean getPage4Exists()
	{
		return getPage4Exists(getContext());
	}

	/**
	 * @param context
	 * @return value of Page4Exists
	 */
	public final java.lang.Boolean getPage4Exists(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page4Exists.toString());
	}

	/**
	 * Set value of Page4Exists
	 * @param page4exists
	 */
	public final void setPage4Exists(java.lang.Boolean page4exists)
	{
		setPage4Exists(getContext(), page4exists);
	}

	/**
	 * Set value of Page4Exists
	 * @param context
	 * @param page4exists
	 */
	public final void setPage4Exists(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page4exists)
	{
		getMendixObject().setValue(context, MemberNames.Page4Exists.toString(), page4exists);
	}

	/**
	 * @return value of Page3Active
	 */
	public final java.lang.Boolean getPage3Active()
	{
		return getPage3Active(getContext());
	}

	/**
	 * @param context
	 * @return value of Page3Active
	 */
	public final java.lang.Boolean getPage3Active(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page3Active.toString());
	}

	/**
	 * Set value of Page3Active
	 * @param page3active
	 */
	public final void setPage3Active(java.lang.Boolean page3active)
	{
		setPage3Active(getContext(), page3active);
	}

	/**
	 * Set value of Page3Active
	 * @param context
	 * @param page3active
	 */
	public final void setPage3Active(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page3active)
	{
		getMendixObject().setValue(context, MemberNames.Page3Active.toString(), page3active);
	}

	/**
	 * @return value of Page3Visited
	 */
	public final java.lang.Boolean getPage3Visited()
	{
		return getPage3Visited(getContext());
	}

	/**
	 * @param context
	 * @return value of Page3Visited
	 */
	public final java.lang.Boolean getPage3Visited(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page3Visited.toString());
	}

	/**
	 * Set value of Page3Visited
	 * @param page3visited
	 */
	public final void setPage3Visited(java.lang.Boolean page3visited)
	{
		setPage3Visited(getContext(), page3visited);
	}

	/**
	 * Set value of Page3Visited
	 * @param context
	 * @param page3visited
	 */
	public final void setPage3Visited(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page3visited)
	{
		getMendixObject().setValue(context, MemberNames.Page3Visited.toString(), page3visited);
	}

	/**
	 * @return value of Page4Active
	 */
	public final java.lang.Boolean getPage4Active()
	{
		return getPage4Active(getContext());
	}

	/**
	 * @param context
	 * @return value of Page4Active
	 */
	public final java.lang.Boolean getPage4Active(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page4Active.toString());
	}

	/**
	 * Set value of Page4Active
	 * @param page4active
	 */
	public final void setPage4Active(java.lang.Boolean page4active)
	{
		setPage4Active(getContext(), page4active);
	}

	/**
	 * Set value of Page4Active
	 * @param context
	 * @param page4active
	 */
	public final void setPage4Active(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page4active)
	{
		getMendixObject().setValue(context, MemberNames.Page4Active.toString(), page4active);
	}

	/**
	 * @return value of Page4Visited
	 */
	public final java.lang.Boolean getPage4Visited()
	{
		return getPage4Visited(getContext());
	}

	/**
	 * @param context
	 * @return value of Page4Visited
	 */
	public final java.lang.Boolean getPage4Visited(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Page4Visited.toString());
	}

	/**
	 * Set value of Page4Visited
	 * @param page4visited
	 */
	public final void setPage4Visited(java.lang.Boolean page4visited)
	{
		setPage4Visited(getContext(), page4visited);
	}

	/**
	 * Set value of Page4Visited
	 * @param context
	 * @param page4visited
	 */
	public final void setPage4Visited(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean page4visited)
	{
		getMendixObject().setValue(context, MemberNames.Page4Visited.toString(), page4visited);
	}

	/**
	 * @return value of PageNav_Page
	 */
	public final questionnaire.proxies.Page getPageNav_Page() throws com.mendix.core.CoreException
	{
		return getPageNav_Page(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNav_Page
	 */
	public final questionnaire.proxies.Page getPageNav_Page(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.Page result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PageNav_Page.toString());
		if (identifier != null)
			result = questionnaire.proxies.Page.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PageNav_Page
	 * @param pagenav_page
	 */
	public final void setPageNav_Page(questionnaire.proxies.Page pagenav_page)
	{
		setPageNav_Page(getContext(), pagenav_page);
	}

	/**
	 * Set value of PageNav_Page
	 * @param context
	 * @param pagenav_page
	 */
	public final void setPageNav_Page(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Page pagenav_page)
	{
		if (pagenav_page == null)
			getMendixObject().setValue(context, MemberNames.PageNav_Page.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PageNav_Page.toString(), pagenav_page.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pageNavMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.PageNav that = (questionnaire.proxies.PageNav) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.PageNav";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
