// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class QuestionnaireConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject questionnaireConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.QuestionnaireConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RevisionNumber("RevisionNumber"),
		Title("Title"),
		Description("Description"),
		State("State"),
		PublishedOnce("PublishedOnce"),
		LastStateChange("LastStateChange"),
		LastStateChangeString("LastStateChangeString"),
		Respondents("Respondents"),
		ConfirmedAction("ConfirmedAction"),
		Category("Category"),
		QuestionnaireConfig_QuestionnaireSet("Questionnaire.QuestionnaireConfig_QuestionnaireSet"),
		QuestionnaireConfig_QuestionnaireConfig_DownloadResults("Questionnaire.QuestionnaireConfig_QuestionnaireConfig_DownloadResults");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.QuestionnaireConfig"));
	}

	protected QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject questionnaireConfigMendixObject)
	{
		if (questionnaireConfigMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.QuestionnaireConfig", questionnaireConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.QuestionnaireConfig");

		this.questionnaireConfigMendixObject = questionnaireConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'QuestionnaireConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.QuestionnaireConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.QuestionnaireConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.QuestionnaireConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.QuestionnaireConfig(context, mendixObject);
	}

	public static questionnaire.proxies.QuestionnaireConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.QuestionnaireConfig.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.QuestionnaireConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.QuestionnaireConfig> result = new java.util.ArrayList<questionnaire.proxies.QuestionnaireConfig>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.QuestionnaireConfig" + xpathConstraint))
			result.add(questionnaire.proxies.QuestionnaireConfig.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RevisionNumber
	 */
	public final java.lang.Integer getRevisionNumber()
	{
		return getRevisionNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of RevisionNumber
	 */
	public final java.lang.Integer getRevisionNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RevisionNumber.toString());
	}

	/**
	 * Set value of RevisionNumber
	 * @param revisionnumber
	 */
	public final void setRevisionNumber(java.lang.Integer revisionnumber)
	{
		setRevisionNumber(getContext(), revisionnumber);
	}

	/**
	 * Set value of RevisionNumber
	 * @param context
	 * @param revisionnumber
	 */
	public final void setRevisionNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer revisionnumber)
	{
		getMendixObject().setValue(context, MemberNames.RevisionNumber.toString(), revisionnumber);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final questionnaire.proxies.State getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final questionnaire.proxies.State getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.State.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(questionnaire.proxies.State state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.State state)
	{
		if (state != null)
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		else
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
	}

	/**
	 * @return value of PublishedOnce
	 */
	public final java.lang.Boolean getPublishedOnce()
	{
		return getPublishedOnce(getContext());
	}

	/**
	 * @param context
	 * @return value of PublishedOnce
	 */
	public final java.lang.Boolean getPublishedOnce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PublishedOnce.toString());
	}

	/**
	 * Set value of PublishedOnce
	 * @param publishedonce
	 */
	public final void setPublishedOnce(java.lang.Boolean publishedonce)
	{
		setPublishedOnce(getContext(), publishedonce);
	}

	/**
	 * Set value of PublishedOnce
	 * @param context
	 * @param publishedonce
	 */
	public final void setPublishedOnce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean publishedonce)
	{
		getMendixObject().setValue(context, MemberNames.PublishedOnce.toString(), publishedonce);
	}

	/**
	 * @return value of LastStateChange
	 */
	public final java.util.Date getLastStateChange()
	{
		return getLastStateChange(getContext());
	}

	/**
	 * @param context
	 * @return value of LastStateChange
	 */
	public final java.util.Date getLastStateChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastStateChange.toString());
	}

	/**
	 * Set value of LastStateChange
	 * @param laststatechange
	 */
	public final void setLastStateChange(java.util.Date laststatechange)
	{
		setLastStateChange(getContext(), laststatechange);
	}

	/**
	 * Set value of LastStateChange
	 * @param context
	 * @param laststatechange
	 */
	public final void setLastStateChange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date laststatechange)
	{
		getMendixObject().setValue(context, MemberNames.LastStateChange.toString(), laststatechange);
	}

	/**
	 * @return value of LastStateChangeString
	 */
	public final java.lang.String getLastStateChangeString()
	{
		return getLastStateChangeString(getContext());
	}

	/**
	 * @param context
	 * @return value of LastStateChangeString
	 */
	public final java.lang.String getLastStateChangeString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastStateChangeString.toString());
	}

	/**
	 * Set value of LastStateChangeString
	 * @param laststatechangestring
	 */
	public final void setLastStateChangeString(java.lang.String laststatechangestring)
	{
		setLastStateChangeString(getContext(), laststatechangestring);
	}

	/**
	 * Set value of LastStateChangeString
	 * @param context
	 * @param laststatechangestring
	 */
	public final void setLastStateChangeString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String laststatechangestring)
	{
		getMendixObject().setValue(context, MemberNames.LastStateChangeString.toString(), laststatechangestring);
	}

	/**
	 * @return value of Respondents
	 */
	public final java.lang.Long getRespondents()
	{
		return getRespondents(getContext());
	}

	/**
	 * @param context
	 * @return value of Respondents
	 */
	public final java.lang.Long getRespondents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Respondents.toString());
	}

	/**
	 * Set value of Respondents
	 * @param respondents
	 */
	public final void setRespondents(java.lang.Long respondents)
	{
		setRespondents(getContext(), respondents);
	}

	/**
	 * Set value of Respondents
	 * @param context
	 * @param respondents
	 */
	public final void setRespondents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long respondents)
	{
		getMendixObject().setValue(context, MemberNames.Respondents.toString(), respondents);
	}

	/**
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction()
	{
		return getConfirmedAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmedAction
	 */
	public final java.lang.Boolean getConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ConfirmedAction.toString());
	}

	/**
	 * Set value of ConfirmedAction
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(java.lang.Boolean confirmedaction)
	{
		setConfirmedAction(getContext(), confirmedaction);
	}

	/**
	 * Set value of ConfirmedAction
	 * @param context
	 * @param confirmedaction
	 */
	public final void setConfirmedAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean confirmedaction)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmedAction.toString(), confirmedaction);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final questionnaire.proxies.Category getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final questionnaire.proxies.Category getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Category.toString());
		if (obj == null)
			return null;

		return questionnaire.proxies.Category.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(questionnaire.proxies.Category category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.Category category)
	{
		if (category != null)
			getMendixObject().setValue(context, MemberNames.Category.toString(), category.toString());
		else
			getMendixObject().setValue(context, MemberNames.Category.toString(), null);
	}

	/**
	 * @return value of QuestionnaireConfig_QuestionnaireSet
	 */
	public final questionnaire.proxies.QuestionnaireSet getQuestionnaireConfig_QuestionnaireSet() throws com.mendix.core.CoreException
	{
		return getQuestionnaireConfig_QuestionnaireSet(getContext());
	}

	/**
	 * @param context
	 * @return value of QuestionnaireConfig_QuestionnaireSet
	 */
	public final questionnaire.proxies.QuestionnaireSet getQuestionnaireConfig_QuestionnaireSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.QuestionnaireSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QuestionnaireConfig_QuestionnaireSet.toString());
		if (identifier != null)
			result = questionnaire.proxies.QuestionnaireSet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of QuestionnaireConfig_QuestionnaireSet
	 * @param questionnaireconfig_questionnaireset
	 */
	public final void setQuestionnaireConfig_QuestionnaireSet(questionnaire.proxies.QuestionnaireSet questionnaireconfig_questionnaireset)
	{
		setQuestionnaireConfig_QuestionnaireSet(getContext(), questionnaireconfig_questionnaireset);
	}

	/**
	 * Set value of QuestionnaireConfig_QuestionnaireSet
	 * @param context
	 * @param questionnaireconfig_questionnaireset
	 */
	public final void setQuestionnaireConfig_QuestionnaireSet(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.QuestionnaireSet questionnaireconfig_questionnaireset)
	{
		if (questionnaireconfig_questionnaireset == null)
			getMendixObject().setValue(context, MemberNames.QuestionnaireConfig_QuestionnaireSet.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.QuestionnaireConfig_QuestionnaireSet.toString(), questionnaireconfig_questionnaireset.getMendixObject().getId());
	}

	/**
	 * @return value of QuestionnaireConfig_QuestionnaireConfig_DownloadResults
	 */
	public final questionnaire.proxies.QuestionnaireConfig getQuestionnaireConfig_QuestionnaireConfig_DownloadResults() throws com.mendix.core.CoreException
	{
		return getQuestionnaireConfig_QuestionnaireConfig_DownloadResults(getContext());
	}

	/**
	 * @param context
	 * @return value of QuestionnaireConfig_QuestionnaireConfig_DownloadResults
	 */
	public final questionnaire.proxies.QuestionnaireConfig getQuestionnaireConfig_QuestionnaireConfig_DownloadResults(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.QuestionnaireConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QuestionnaireConfig_QuestionnaireConfig_DownloadResults.toString());
		if (identifier != null)
			result = questionnaire.proxies.QuestionnaireConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of QuestionnaireConfig_QuestionnaireConfig_DownloadResults
	 * @param questionnaireconfig_questionnaireconfig_downloadresults
	 */
	public final void setQuestionnaireConfig_QuestionnaireConfig_DownloadResults(questionnaire.proxies.QuestionnaireConfig questionnaireconfig_questionnaireconfig_downloadresults)
	{
		setQuestionnaireConfig_QuestionnaireConfig_DownloadResults(getContext(), questionnaireconfig_questionnaireconfig_downloadresults);
	}

	/**
	 * Set value of QuestionnaireConfig_QuestionnaireConfig_DownloadResults
	 * @param context
	 * @param questionnaireconfig_questionnaireconfig_downloadresults
	 */
	public final void setQuestionnaireConfig_QuestionnaireConfig_DownloadResults(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.QuestionnaireConfig questionnaireconfig_questionnaireconfig_downloadresults)
	{
		if (questionnaireconfig_questionnaireconfig_downloadresults == null)
			getMendixObject().setValue(context, MemberNames.QuestionnaireConfig_QuestionnaireConfig_DownloadResults.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.QuestionnaireConfig_QuestionnaireConfig_DownloadResults.toString(), questionnaireconfig_questionnaireconfig_downloadresults.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return questionnaireConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.QuestionnaireConfig that = (questionnaire.proxies.QuestionnaireConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.QuestionnaireConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
