// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package questionnaire.proxies;

public class XMLDocumentTemplate extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Questionnaire.XMLDocumentTemplate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		XMLDocumentTemplate_QuestionnaireConfig("Questionnaire.XMLDocumentTemplate_QuestionnaireConfig");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public XMLDocumentTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Questionnaire.XMLDocumentTemplate"));
	}

	protected XMLDocumentTemplate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject xMLDocumentTemplateMendixObject)
	{
		super(context, xMLDocumentTemplateMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Questionnaire.XMLDocumentTemplate", xMLDocumentTemplateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Questionnaire.XMLDocumentTemplate");
	}

	/**
	 * @deprecated Use 'XMLDocumentTemplate.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static questionnaire.proxies.XMLDocumentTemplate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return questionnaire.proxies.XMLDocumentTemplate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static questionnaire.proxies.XMLDocumentTemplate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new questionnaire.proxies.XMLDocumentTemplate(context, mendixObject);
	}

	public static questionnaire.proxies.XMLDocumentTemplate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return questionnaire.proxies.XMLDocumentTemplate.initialize(context, mendixObject);
	}

	public static java.util.List<questionnaire.proxies.XMLDocumentTemplate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<questionnaire.proxies.XMLDocumentTemplate> result = new java.util.ArrayList<questionnaire.proxies.XMLDocumentTemplate>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Questionnaire.XMLDocumentTemplate" + xpathConstraint))
			result.add(questionnaire.proxies.XMLDocumentTemplate.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of XMLDocumentTemplate_QuestionnaireConfig
	 */
	public final questionnaire.proxies.QuestionnaireConfig getXMLDocumentTemplate_QuestionnaireConfig() throws com.mendix.core.CoreException
	{
		return getXMLDocumentTemplate_QuestionnaireConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of XMLDocumentTemplate_QuestionnaireConfig
	 */
	public final questionnaire.proxies.QuestionnaireConfig getXMLDocumentTemplate_QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		questionnaire.proxies.QuestionnaireConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XMLDocumentTemplate_QuestionnaireConfig.toString());
		if (identifier != null)
			result = questionnaire.proxies.QuestionnaireConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XMLDocumentTemplate_QuestionnaireConfig
	 * @param xmldocumenttemplate_questionnaireconfig
	 */
	public final void setXMLDocumentTemplate_QuestionnaireConfig(questionnaire.proxies.QuestionnaireConfig xmldocumenttemplate_questionnaireconfig)
	{
		setXMLDocumentTemplate_QuestionnaireConfig(getContext(), xmldocumenttemplate_questionnaireconfig);
	}

	/**
	 * Set value of XMLDocumentTemplate_QuestionnaireConfig
	 * @param context
	 * @param xmldocumenttemplate_questionnaireconfig
	 */
	public final void setXMLDocumentTemplate_QuestionnaireConfig(com.mendix.systemwideinterfaces.core.IContext context, questionnaire.proxies.QuestionnaireConfig xmldocumenttemplate_questionnaireconfig)
	{
		if (xmldocumenttemplate_questionnaireconfig == null)
			getMendixObject().setValue(context, MemberNames.XMLDocumentTemplate_QuestionnaireConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XMLDocumentTemplate_QuestionnaireConfig.toString(), xmldocumenttemplate_questionnaireconfig.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final questionnaire.proxies.XMLDocumentTemplate that = (questionnaire.proxies.XMLDocumentTemplate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Questionnaire.XMLDocumentTemplate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
