// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package trainingcourse.proxies;

public class Dashboard
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TrainingCourse.Dashboard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NrOfRegistration("NrOfRegistration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dashboard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TrainingCourse.Dashboard"));
	}

	protected Dashboard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject)
	{
		if (dashboardMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TrainingCourse.Dashboard", dashboardMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TrainingCourse.Dashboard");

		this.dashboardMendixObject = dashboardMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dashboard.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static trainingcourse.proxies.Dashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return trainingcourse.proxies.Dashboard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static trainingcourse.proxies.Dashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new trainingcourse.proxies.Dashboard(context, mendixObject);
	}

	public static trainingcourse.proxies.Dashboard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return trainingcourse.proxies.Dashboard.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NrOfRegistration
	 */
	public final java.lang.Integer getNrOfRegistration()
	{
		return getNrOfRegistration(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfRegistration
	 */
	public final java.lang.Integer getNrOfRegistration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrOfRegistration.toString());
	}

	/**
	 * Set value of NrOfRegistration
	 * @param nrofregistration
	 */
	public final void setNrOfRegistration(java.lang.Integer nrofregistration)
	{
		setNrOfRegistration(getContext(), nrofregistration);
	}

	/**
	 * Set value of NrOfRegistration
	 * @param context
	 * @param nrofregistration
	 */
	public final void setNrOfRegistration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nrofregistration)
	{
		getMendixObject().setValue(context, MemberNames.NrOfRegistration.toString(), nrofregistration);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboardMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final trainingcourse.proxies.Dashboard that = (trainingcourse.proxies.Dashboard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TrainingCourse.Dashboard";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
