// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies;

public class CSRFToken
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cSRFTokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAPODataConnector.CSRFToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		csrfTokenValue("csrfTokenValue"),
		CSRFToken_Session("SAPODataConnector.CSRFToken_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CSRFToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAPODataConnector.CSRFToken"));
	}

	protected CSRFToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cSRFTokenMendixObject)
	{
		if (cSRFTokenMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAPODataConnector.CSRFToken", cSRFTokenMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAPODataConnector.CSRFToken");

		this.cSRFTokenMendixObject = cSRFTokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CSRFToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sapodataconnector.proxies.CSRFToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sapodataconnector.proxies.CSRFToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sapodataconnector.proxies.CSRFToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sapodataconnector.proxies.CSRFToken(context, mendixObject);
	}

	public static sapodataconnector.proxies.CSRFToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sapodataconnector.proxies.CSRFToken.initialize(context, mendixObject);
	}

	public static java.util.List<sapodataconnector.proxies.CSRFToken> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sapodataconnector.proxies.CSRFToken> result = new java.util.ArrayList<sapodataconnector.proxies.CSRFToken>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAPODataConnector.CSRFToken" + xpathConstraint))
			result.add(sapodataconnector.proxies.CSRFToken.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of csrfTokenValue
	 */
	public final java.lang.String getcsrfTokenValue()
	{
		return getcsrfTokenValue(getContext());
	}

	/**
	 * @param context
	 * @return value of csrfTokenValue
	 */
	public final java.lang.String getcsrfTokenValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.csrfTokenValue.toString());
	}

	/**
	 * Set value of csrfTokenValue
	 * @param csrftokenvalue
	 */
	public final void setcsrfTokenValue(java.lang.String csrftokenvalue)
	{
		setcsrfTokenValue(getContext(), csrftokenvalue);
	}

	/**
	 * Set value of csrfTokenValue
	 * @param context
	 * @param csrftokenvalue
	 */
	public final void setcsrfTokenValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csrftokenvalue)
	{
		getMendixObject().setValue(context, MemberNames.csrfTokenValue.toString(), csrftokenvalue);
	}

	/**
	 * @return value of CSRFToken_Session
	 */
	public final system.proxies.Session getCSRFToken_Session() throws com.mendix.core.CoreException
	{
		return getCSRFToken_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of CSRFToken_Session
	 */
	public final system.proxies.Session getCSRFToken_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CSRFToken_Session.toString());
		if (identifier != null)
			result = system.proxies.Session.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CSRFToken_Session
	 * @param csrftoken_session
	 */
	public final void setCSRFToken_Session(system.proxies.Session csrftoken_session)
	{
		setCSRFToken_Session(getContext(), csrftoken_session);
	}

	/**
	 * Set value of CSRFToken_Session
	 * @param context
	 * @param csrftoken_session
	 */
	public final void setCSRFToken_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session csrftoken_session)
	{
		if (csrftoken_session == null)
			getMendixObject().setValue(context, MemberNames.CSRFToken_Session.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CSRFToken_Session.toString(), csrftoken_session.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cSRFTokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sapodataconnector.proxies.CSRFToken that = (sapodataconnector.proxies.CSRFToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAPODataConnector.CSRFToken";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
