// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package zgws_cust_get_srv.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ZGWS_cust_GET_SRV module

	public static java.lang.String getZGWS_cust_GET_SRV()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ZGWS_cust_GET_SRV.ZGWS_cust_GET_SRV");
	}
}