// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.request.RequestParameterUtil;

public class AddHeader extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __requestParameter;
	private sapodataconnector.proxies.RequestParams requestParameter;
	private java.lang.String name;
	private java.lang.String value;

	public AddHeader(IContext context, IMendixObject requestParameter, java.lang.String name, java.lang.String value)
	{
		super(context);
		this.__requestParameter = requestParameter;
		this.name = name;
		this.value = value;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.requestParameter = __requestParameter == null ? null : sapodataconnector.proxies.RequestParams.initialize(getContext(), __requestParameter);

		// BEGIN USER CODE
		if (requestParameter == null) {
			throw new IllegalArgumentException("RequestParams is not provided");
		}

		RequestParameterUtil.change(getContext(), requestParameter)
			.addHeader(name, value)
			.build();

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "AddHeader";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
