// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.proxies.CloudConnectorInfo;
import sapodataconnector.utils.proxy.ProxyInformation;
import sapodataconnector.utils.proxy.ProxyInformationFactory;

public class GetCloudConnectorInfo extends CustomJavaAction<IMendixObject>
{
	public GetCloudConnectorInfo(IContext context)
	{
		super(context);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ProxyInformation proxyInfo = ProxyInformationFactory.getProxyInformation(getContext());

		if (proxyInfo == null) {
			LOGGER.warn("GetCloudConnectorInfo could not find VCAP information. Cloud Connector not enabled?");
			return null;
		}

		CloudConnectorInfo result = new CloudConnectorInfo(getContext());
		result.setProxyBearerToken(proxyInfo.getProxyCredentials());
		result.setProxyHost(proxyInfo.getProxyHost());
		result.setProxyPort(proxyInfo.getProxyPort());
		return result.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetCloudConnectorInfo";
	}

	// BEGIN EXTRA CODE
	private final static ILogNode LOGGER = Core.getLogger(sapodataconnector.proxies.constants.Constants.getLogNode());
	// END EXTRA CODE
}
