// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import java.util.ArrayList;
import java.util.List;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.proxies.OdataObject;
import sapodataconnector.proxies.constants.Constants;
import sapodataconnector.utils.ODataClientBuilder;
import sapodataconnector.utils.ODataRequestBuilder;
import sapodataconnector.utils.ODataResponseHandler;
import sapodataconnector.utils.ODataTypeChecker;
import sapodataconnector.utils.ToMendixSerializer;

public class GetList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String query;
	private java.lang.String responseType;
	private IMendixObject __requestParameters;
	private sapodataconnector.proxies.RequestParams requestParameters;
	private IMendixObject __parent;
	private sapodataconnector.proxies.OdataObject parent;
	private IMendixObject __resultInfo;
	private sapodataconnector.proxies.ResultInfo resultInfo;
	private java.lang.Boolean useSAPCloudConnector;

	public GetList(IContext context, java.lang.String query, java.lang.String responseType, IMendixObject requestParameters, IMendixObject parent, IMendixObject resultInfo, java.lang.Boolean useSAPCloudConnector)
	{
		super(context);
		this.query = query;
		this.responseType = responseType;
		this.__requestParameters = requestParameters;
		this.__parent = parent;
		this.__resultInfo = resultInfo;
		this.useSAPCloudConnector = useSAPCloudConnector;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.requestParameters = __requestParameters == null ? null : sapodataconnector.proxies.RequestParams.initialize(getContext(), __requestParameters);

		this.parent = __parent == null ? null : sapodataconnector.proxies.OdataObject.initialize(getContext(), __parent);

		this.resultInfo = __resultInfo == null ? null : sapodataconnector.proxies.ResultInfo.initialize(getContext(), __resultInfo);

		// BEGIN USER CODE
		if(LOGGER.isDebugEnabled()) {
			LOGGER.debug(new StringBuilder(getContext().getSession().getId().toString())
					.append("|GET|List, query: ")
					.append(query)
					.toString());
		}

		ODataTypeChecker.checkDescendantOf(Core.getMetaObject(responseType), OdataObject.entityName);

		final HttpGet httpGet = ODataRequestBuilder.builder()
				.get(query)
				.setContext(getContext())
				.fetchCSRFToken()
				.setReqeuestHeader(requestParameters)
				.build();

		String response = null;
		try (final CloseableHttpClient httpClient = ODataClientBuilder.builder()
				.setContext(getContext())
				.setRequestParameters(requestParameters)
				.useCloudConnector(this.useSAPCloudConnector)
				.build()) {

			response = httpClient.execute(httpGet, new ODataResponseHandler("GET", LOGGER, getContext()));
		}

		final List<IMendixObject> resultList = new ArrayList<>();
		ToMendixSerializer.createNewMendixObjectList(getContext(), responseType, resultList, resultInfo, parent, response);

		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetList";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode LOGGER = Core.getLogger(Constants.getLogNode());
	// END EXTRA CODE
}
