// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapodataconnector.actions;

import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import sapodataconnector.proxies.constants.Constants;
import sapodataconnector.utils.ExpectedHttpResultOptional;
import sapodataconnector.utils.ODataClientBuilder;
import sapodataconnector.utils.ODataRequestBuilder;
import sapodataconnector.utils.ODataResponseHandler;
import sapodataconnector.utils.ToMendixSerializer;

public class Refresh extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __odataObject;
	private sapodataconnector.proxies.OdataObject odataObject;
	private IMendixObject __requestParameters;
	private sapodataconnector.proxies.RequestParams requestParameters;
	private java.lang.Boolean useSAPCloudConnector;

	public Refresh(IContext context, IMendixObject odataObject, IMendixObject requestParameters, java.lang.Boolean useSAPCloudConnector)
	{
		super(context);
		this.__odataObject = odataObject;
		this.__requestParameters = requestParameters;
		this.useSAPCloudConnector = useSAPCloudConnector;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.odataObject = __odataObject == null ? null : sapodataconnector.proxies.OdataObject.initialize(getContext(), __odataObject);

		this.requestParameters = __requestParameters == null ? null : sapodataconnector.proxies.RequestParams.initialize(getContext(), __requestParameters);

		// BEGIN USER CODE
		if(LOGGER.isDebugEnabled()) {
			LOGGER.debug(new StringBuilder(getContext().getSession().getId().toString())
					.append("|REFRESH|single, query: ")
					.append(odataObject.getmeta_objectURI())
					.toString());
		}

		final HttpGet httpGet = ODataRequestBuilder.builder()
				.get(odataObject.getmeta_objectURI())
				.setContext(getContext())
				.setReqeuestHeader(requestParameters)
				.fetchCSRFToken()
				.build();

		String response = null;
		try (final CloseableHttpClient httpClient = ODataClientBuilder.builder()
				.setContext(getContext())
				.setRequestParameters(requestParameters)
				.useCloudConnector(this.useSAPCloudConnector)
				.build()){

			response = httpClient.execute(httpGet, new ODataResponseHandler("REFRESH", LOGGER, getContext(),
					ExpectedHttpResultOptional.ofNullable(requestParameters).getExpectedHttpResult()));
		}

		if (response == null) {
			throw new MendixException("This call has not been performed correctly, please make sure that this action is supported by the service provider.");
		}

		final JSONObject jsonObjArray = new JSONObject(response).getJSONObject("d");
		if (jsonObjArray == null) {
			throw new MendixException("Expectinng exactly one result, got nothing");
		}

		ToMendixSerializer.updateMendixObject(getContext(), jsonObjArray, __odataObject);

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Refresh";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode LOGGER = Core.getLogger(Constants.getLogNode());
	// END EXTRA CODE
}
